/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AbandonedAccountDto
 */
export interface AbandonedAccountDto {
    /**
     * Account ID
     * @type {string}
     * @memberof AbandonedAccountDto
     */
    accountId: string;
    /**
     * Mastodon account name
     * @type {string}
     * @memberof AbandonedAccountDto
     */
    accountName: string;
    /**
     * Mastodon server URL
     * @type {string}
     * @memberof AbandonedAccountDto
     */
    serverURL: string;
    /**
     * Account owner email
     * @type {string}
     * @memberof AbandonedAccountDto
     */
    ownerEmail: string;
    /**
     * Last login date of the owner
     * @type {string}
     * @memberof AbandonedAccountDto
     */
    lastLoginDate: string | null;
    /**
     * Whether a deletion notice has been sent
     * @type {boolean}
     * @memberof AbandonedAccountDto
     */
    deletionNoticeSent: boolean;
}

/**
 * Check if a given object implements the AbandonedAccountDto interface.
 */
export function instanceOfAbandonedAccountDto(value: object): value is AbandonedAccountDto {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('accountName' in value) || value['accountName'] === undefined) return false;
    if (!('serverURL' in value) || value['serverURL'] === undefined) return false;
    if (!('ownerEmail' in value) || value['ownerEmail'] === undefined) return false;
    if (!('lastLoginDate' in value) || value['lastLoginDate'] === undefined) return false;
    if (!('deletionNoticeSent' in value) || value['deletionNoticeSent'] === undefined) return false;
    return true;
}

export function AbandonedAccountDtoFromJSON(json: any): AbandonedAccountDto {
    return AbandonedAccountDtoFromJSONTyped(json, false);
}

export function AbandonedAccountDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AbandonedAccountDto {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'accountName': json['accountName'],
        'serverURL': json['serverURL'],
        'ownerEmail': json['ownerEmail'],
        'lastLoginDate': json['lastLoginDate'],
        'deletionNoticeSent': json['deletionNoticeSent'],
    };
}

export function AbandonedAccountDtoToJSON(json: any): AbandonedAccountDto {
    return AbandonedAccountDtoToJSONTyped(json, false);
}

export function AbandonedAccountDtoToJSONTyped(value?: AbandonedAccountDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'accountName': value['accountName'],
        'serverURL': value['serverURL'],
        'ownerEmail': value['ownerEmail'],
        'lastLoginDate': value['lastLoginDate'],
        'deletionNoticeSent': value['deletionNoticeSent'],
    };
}

