/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountsControllerConnect200Response
 */
export interface AccountsControllerConnect200Response {
    /**
     * 
     * @type {string}
     * @memberof AccountsControllerConnect200Response
     */
    redirectUrl?: string;
}

/**
 * Check if a given object implements the AccountsControllerConnect200Response interface.
 */
export function instanceOfAccountsControllerConnect200Response(value: object): value is AccountsControllerConnect200Response {
    return true;
}

export function AccountsControllerConnect200ResponseFromJSON(json: any): AccountsControllerConnect200Response {
    return AccountsControllerConnect200ResponseFromJSONTyped(json, false);
}

export function AccountsControllerConnect200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountsControllerConnect200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'redirectUrl': json['redirectUrl'] == null ? undefined : json['redirectUrl'],
    };
}

export function AccountsControllerConnect200ResponseToJSON(json: any): AccountsControllerConnect200Response {
    return AccountsControllerConnect200ResponseToJSONTyped(json, false);
}

export function AccountsControllerConnect200ResponseToJSONTyped(value?: AccountsControllerConnect200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'redirectUrl': value['redirectUrl'],
    };
}

