/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServerDistributionDto } from './ServerDistributionDto';
import {
    ServerDistributionDtoFromJSON,
    ServerDistributionDtoFromJSONTyped,
    ServerDistributionDtoToJSON,
    ServerDistributionDtoToJSONTyped,
} from './ServerDistributionDto';

/**
 * 
 * @export
 * @interface AccountMetricsDto
 */
export interface AccountMetricsDto {
    /**
     * Total number of accounts
     * @type {number}
     * @memberof AccountMetricsDto
     */
    totalCount: number;
    /**
     * Number of accounts with setup complete
     * @type {number}
     * @memberof AccountMetricsDto
     */
    setupCompleteCount: number;
    /**
     * Number of accounts with setup incomplete
     * @type {number}
     * @memberof AccountMetricsDto
     */
    setupIncompleteCount: number;
    /**
     * Number of active accounts
     * @type {number}
     * @memberof AccountMetricsDto
     */
    activeCount: number;
    /**
     * Number of inactive accounts
     * @type {number}
     * @memberof AccountMetricsDto
     */
    inactiveCount: number;
    /**
     * Distribution of accounts by Mastodon server
     * @type {Array<ServerDistributionDto>}
     * @memberof AccountMetricsDto
     */
    serverDistribution: Array<ServerDistributionDto>;
}

/**
 * Check if a given object implements the AccountMetricsDto interface.
 */
export function instanceOfAccountMetricsDto(value: object): value is AccountMetricsDto {
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('setupCompleteCount' in value) || value['setupCompleteCount'] === undefined) return false;
    if (!('setupIncompleteCount' in value) || value['setupIncompleteCount'] === undefined) return false;
    if (!('activeCount' in value) || value['activeCount'] === undefined) return false;
    if (!('inactiveCount' in value) || value['inactiveCount'] === undefined) return false;
    if (!('serverDistribution' in value) || value['serverDistribution'] === undefined) return false;
    return true;
}

export function AccountMetricsDtoFromJSON(json: any): AccountMetricsDto {
    return AccountMetricsDtoFromJSONTyped(json, false);
}

export function AccountMetricsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountMetricsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'totalCount': json['totalCount'],
        'setupCompleteCount': json['setupCompleteCount'],
        'setupIncompleteCount': json['setupIncompleteCount'],
        'activeCount': json['activeCount'],
        'inactiveCount': json['inactiveCount'],
        'serverDistribution': ((json['serverDistribution'] as Array<any>).map(ServerDistributionDtoFromJSON)),
    };
}

export function AccountMetricsDtoToJSON(json: any): AccountMetricsDto {
    return AccountMetricsDtoToJSONTyped(json, false);
}

export function AccountMetricsDtoToJSONTyped(value?: AccountMetricsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalCount': value['totalCount'],
        'setupCompleteCount': value['setupCompleteCount'],
        'setupIncompleteCount': value['setupIncompleteCount'],
        'activeCount': value['activeCount'],
        'inactiveCount': value['inactiveCount'],
        'serverDistribution': ((value['serverDistribution'] as Array<any>).map(ServerDistributionDtoToJSON)),
    };
}

