/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IncompleteAccountDto } from './IncompleteAccountDto';
import {
    IncompleteAccountDtoFromJSON,
    IncompleteAccountDtoFromJSONTyped,
    IncompleteAccountDtoToJSON,
    IncompleteAccountDtoToJSONTyped,
} from './IncompleteAccountDto';
import type { AbandonedAccountDto } from './AbandonedAccountDto';
import {
    AbandonedAccountDtoFromJSON,
    AbandonedAccountDtoFromJSONTyped,
    AbandonedAccountDtoToJSON,
    AbandonedAccountDtoToJSONTyped,
} from './AbandonedAccountDto';
import type { StaleAccountDto } from './StaleAccountDto';
import {
    StaleAccountDtoFromJSON,
    StaleAccountDtoFromJSONTyped,
    StaleAccountDtoToJSON,
    StaleAccountDtoToJSONTyped,
} from './StaleAccountDto';

/**
 * 
 * @export
 * @interface AccountHealthResponseDto
 */
export interface AccountHealthResponseDto {
    /**
     * When the health snapshot was generated
     * @type {string}
     * @memberof AccountHealthResponseDto
     */
    generatedAt?: string;
    /**
     * Accounts with stale data collection
     * @type {Array<StaleAccountDto>}
     * @memberof AccountHealthResponseDto
     */
    staleAccounts: Array<StaleAccountDto>;
    /**
     * Accounts with incomplete setup
     * @type {Array<IncompleteAccountDto>}
     * @memberof AccountHealthResponseDto
     */
    incompleteAccounts: Array<IncompleteAccountDto>;
    /**
     * Accounts belonging to users who have not logged in recently
     * @type {Array<AbandonedAccountDto>}
     * @memberof AccountHealthResponseDto
     */
    abandonedAccounts: Array<AbandonedAccountDto>;
}

/**
 * Check if a given object implements the AccountHealthResponseDto interface.
 */
export function instanceOfAccountHealthResponseDto(value: object): value is AccountHealthResponseDto {
    if (!('staleAccounts' in value) || value['staleAccounts'] === undefined) return false;
    if (!('incompleteAccounts' in value) || value['incompleteAccounts'] === undefined) return false;
    if (!('abandonedAccounts' in value) || value['abandonedAccounts'] === undefined) return false;
    return true;
}

export function AccountHealthResponseDtoFromJSON(json: any): AccountHealthResponseDto {
    return AccountHealthResponseDtoFromJSONTyped(json, false);
}

export function AccountHealthResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountHealthResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'generatedAt': json['generatedAt'] == null ? undefined : json['generatedAt'],
        'staleAccounts': ((json['staleAccounts'] as Array<any>).map(StaleAccountDtoFromJSON)),
        'incompleteAccounts': ((json['incompleteAccounts'] as Array<any>).map(IncompleteAccountDtoFromJSON)),
        'abandonedAccounts': ((json['abandonedAccounts'] as Array<any>).map(AbandonedAccountDtoFromJSON)),
    };
}

export function AccountHealthResponseDtoToJSON(json: any): AccountHealthResponseDto {
    return AccountHealthResponseDtoToJSONTyped(json, false);
}

export function AccountHealthResponseDtoToJSONTyped(value?: AccountHealthResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'generatedAt': value['generatedAt'],
        'staleAccounts': ((value['staleAccounts'] as Array<any>).map(StaleAccountDtoToJSON)),
        'incompleteAccounts': ((value['incompleteAccounts'] as Array<any>).map(IncompleteAccountDtoToJSON)),
        'abandonedAccounts': ((value['abandonedAccounts'] as Array<any>).map(AbandonedAccountDtoToJSON)),
    };
}

