/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountSummaryDto
 */
export interface AccountSummaryDto {
    /**
     * Account ID
     * @type {string}
     * @memberof AccountSummaryDto
     */
    id: string;
    /**
     * Mastodon server URL
     * @type {string}
     * @memberof AccountSummaryDto
     */
    serverURL: string;
    /**
     * Account name on the server
     * @type {string}
     * @memberof AccountSummaryDto
     */
    accountName?: string;
    /**
     * Username on the server
     * @type {string}
     * @memberof AccountSummaryDto
     */
    username?: string;
    /**
     * Indicates if the account is active
     * @type {boolean}
     * @memberof AccountSummaryDto
     */
    isActive: boolean;
    /**
     * Indicates if the account setup is complete
     * @type {boolean}
     * @memberof AccountSummaryDto
     */
    setupComplete: boolean;
    /**
     * Timestamp of account creation
     * @type {Date}
     * @memberof AccountSummaryDto
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the AccountSummaryDto interface.
 */
export function instanceOfAccountSummaryDto(value: object): value is AccountSummaryDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('serverURL' in value) || value['serverURL'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('setupComplete' in value) || value['setupComplete'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function AccountSummaryDtoFromJSON(json: any): AccountSummaryDto {
    return AccountSummaryDtoFromJSONTyped(json, false);
}

export function AccountSummaryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountSummaryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'serverURL': json['serverURL'],
        'accountName': json['accountName'] == null ? undefined : json['accountName'],
        'username': json['username'] == null ? undefined : json['username'],
        'isActive': json['isActive'],
        'setupComplete': json['setupComplete'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function AccountSummaryDtoToJSON(json: any): AccountSummaryDto {
    return AccountSummaryDtoToJSONTyped(json, false);
}

export function AccountSummaryDtoToJSONTyped(value?: AccountSummaryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'serverURL': value['serverURL'],
        'accountName': value['accountName'],
        'username': value['username'],
        'isActive': value['isActive'],
        'setupComplete': value['setupComplete'],
        'createdAt': ((value['createdAt']).toISOString()),
    };
}

