/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminAccountOwnerDto } from './AdminAccountOwnerDto';
import {
    AdminAccountOwnerDtoFromJSON,
    AdminAccountOwnerDtoFromJSONTyped,
    AdminAccountOwnerDtoToJSON,
    AdminAccountOwnerDtoToJSONTyped,
} from './AdminAccountOwnerDto';

/**
 * 
 * @export
 * @interface AdminAccountItemDto
 */
export interface AdminAccountItemDto {
    /**
     * Account ID
     * @type {string}
     * @memberof AdminAccountItemDto
     */
    id: string;
    /**
     * Mastodon server URL
     * @type {string}
     * @memberof AdminAccountItemDto
     */
    serverURL: string;
    /**
     * Account name (e.g. @user@server)
     * @type {string}
     * @memberof AdminAccountItemDto
     */
    accountName?: string;
    /**
     * Username on the Mastodon server
     * @type {string}
     * @memberof AdminAccountItemDto
     */
    username?: string;
    /**
     * Display name
     * @type {string}
     * @memberof AdminAccountItemDto
     */
    name?: string;
    /**
     * Avatar URL
     * @type {string}
     * @memberof AdminAccountItemDto
     */
    avatarURL?: string;
    /**
     * Whether the account is active
     * @type {boolean}
     * @memberof AdminAccountItemDto
     */
    isActive: boolean;
    /**
     * Whether account setup is complete
     * @type {boolean}
     * @memberof AdminAccountItemDto
     */
    setupComplete: boolean;
    /**
     * Account creation date
     * @type {string}
     * @memberof AdminAccountItemDto
     */
    createdAt: string;
    /**
     * Account owner info
     * @type {AdminAccountOwnerDto}
     * @memberof AdminAccountItemDto
     */
    owner: AdminAccountOwnerDto;
}

/**
 * Check if a given object implements the AdminAccountItemDto interface.
 */
export function instanceOfAdminAccountItemDto(value: object): value is AdminAccountItemDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('serverURL' in value) || value['serverURL'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('setupComplete' in value) || value['setupComplete'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('owner' in value) || value['owner'] === undefined) return false;
    return true;
}

export function AdminAccountItemDtoFromJSON(json: any): AdminAccountItemDto {
    return AdminAccountItemDtoFromJSONTyped(json, false);
}

export function AdminAccountItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminAccountItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'serverURL': json['serverURL'],
        'accountName': json['accountName'] == null ? undefined : json['accountName'],
        'username': json['username'] == null ? undefined : json['username'],
        'name': json['name'] == null ? undefined : json['name'],
        'avatarURL': json['avatarURL'] == null ? undefined : json['avatarURL'],
        'isActive': json['isActive'],
        'setupComplete': json['setupComplete'],
        'createdAt': json['createdAt'],
        'owner': AdminAccountOwnerDtoFromJSON(json['owner']),
    };
}

export function AdminAccountItemDtoToJSON(json: any): AdminAccountItemDto {
    return AdminAccountItemDtoToJSONTyped(json, false);
}

export function AdminAccountItemDtoToJSONTyped(value?: AdminAccountItemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'serverURL': value['serverURL'],
        'accountName': value['accountName'],
        'username': value['username'],
        'name': value['name'],
        'avatarURL': value['avatarURL'],
        'isActive': value['isActive'],
        'setupComplete': value['setupComplete'],
        'createdAt': value['createdAt'],
        'owner': AdminAccountOwnerDtoToJSON(value['owner']),
    };
}

