/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminAccountItemDto } from './AdminAccountItemDto';
import {
    AdminAccountItemDtoFromJSON,
    AdminAccountItemDtoFromJSONTyped,
    AdminAccountItemDtoToJSON,
    AdminAccountItemDtoToJSONTyped,
} from './AdminAccountItemDto';

/**
 * 
 * @export
 * @interface AdminAccountsResponseDto
 */
export interface AdminAccountsResponseDto {
    /**
     * List of accounts
     * @type {Array<AdminAccountItemDto>}
     * @memberof AdminAccountsResponseDto
     */
    items: Array<AdminAccountItemDto>;
    /**
     * Total number of matching accounts
     * @type {number}
     * @memberof AdminAccountsResponseDto
     */
    total: number;
    /**
     * Current page number
     * @type {number}
     * @memberof AdminAccountsResponseDto
     */
    page: number;
    /**
     * Items per page
     * @type {number}
     * @memberof AdminAccountsResponseDto
     */
    limit: number;
    /**
     * Total number of pages
     * @type {number}
     * @memberof AdminAccountsResponseDto
     */
    totalPages: number;
}

/**
 * Check if a given object implements the AdminAccountsResponseDto interface.
 */
export function instanceOfAdminAccountsResponseDto(value: object): value is AdminAccountsResponseDto {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    return true;
}

export function AdminAccountsResponseDtoFromJSON(json: any): AdminAccountsResponseDto {
    return AdminAccountsResponseDtoFromJSONTyped(json, false);
}

export function AdminAccountsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminAccountsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(AdminAccountItemDtoFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'limit': json['limit'],
        'totalPages': json['totalPages'],
    };
}

export function AdminAccountsResponseDtoToJSON(json: any): AdminAccountsResponseDto {
    return AdminAccountsResponseDtoToJSONTyped(json, false);
}

export function AdminAccountsResponseDtoToJSONTyped(value?: AdminAccountsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(AdminAccountItemDtoToJSON)),
        'total': value['total'],
        'page': value['page'],
        'limit': value['limit'],
        'totalPages': value['totalPages'],
    };
}

