/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminAccountOwnerDto
 */
export interface AdminAccountOwnerDto {
    /**
     * Owner user ID
     * @type {string}
     * @memberof AdminAccountOwnerDto
     */
    id: string;
    /**
     * Owner email address
     * @type {string}
     * @memberof AdminAccountOwnerDto
     */
    email: string;
}

/**
 * Check if a given object implements the AdminAccountOwnerDto interface.
 */
export function instanceOfAdminAccountOwnerDto(value: object): value is AdminAccountOwnerDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function AdminAccountOwnerDtoFromJSON(json: any): AdminAccountOwnerDto {
    return AdminAccountOwnerDtoFromJSONTyped(json, false);
}

export function AdminAccountOwnerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminAccountOwnerDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
    };
}

export function AdminAccountOwnerDtoToJSON(json: any): AdminAccountOwnerDto {
    return AdminAccountOwnerDtoToJSONTyped(json, false);
}

export function AdminAccountOwnerDtoToJSONTyped(value?: AdminAccountOwnerDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
    };
}

