/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataVolumeMetricsDto } from './DataVolumeMetricsDto';
import {
    DataVolumeMetricsDtoFromJSON,
    DataVolumeMetricsDtoFromJSONTyped,
    DataVolumeMetricsDtoToJSON,
    DataVolumeMetricsDtoToJSONTyped,
} from './DataVolumeMetricsDto';
import type { AccountMetricsDto } from './AccountMetricsDto';
import {
    AccountMetricsDtoFromJSON,
    AccountMetricsDtoFromJSONTyped,
    AccountMetricsDtoToJSON,
    AccountMetricsDtoToJSONTyped,
} from './AccountMetricsDto';
import type { UserMetricsDto } from './UserMetricsDto';
import {
    UserMetricsDtoFromJSON,
    UserMetricsDtoFromJSONTyped,
    UserMetricsDtoToJSON,
    UserMetricsDtoToJSONTyped,
} from './UserMetricsDto';

/**
 * 
 * @export
 * @interface AdminStatsResponseDto
 */
export interface AdminStatsResponseDto {
    /**
     * User-related metrics
     * @type {UserMetricsDto}
     * @memberof AdminStatsResponseDto
     */
    users: UserMetricsDto;
    /**
     * Account-related metrics
     * @type {AccountMetricsDto}
     * @memberof AdminStatsResponseDto
     */
    accounts: AccountMetricsDto;
    /**
     * Data volume metrics
     * @type {DataVolumeMetricsDto}
     * @memberof AdminStatsResponseDto
     */
    dataVolume: DataVolumeMetricsDto;
}

/**
 * Check if a given object implements the AdminStatsResponseDto interface.
 */
export function instanceOfAdminStatsResponseDto(value: object): value is AdminStatsResponseDto {
    if (!('users' in value) || value['users'] === undefined) return false;
    if (!('accounts' in value) || value['accounts'] === undefined) return false;
    if (!('dataVolume' in value) || value['dataVolume'] === undefined) return false;
    return true;
}

export function AdminStatsResponseDtoFromJSON(json: any): AdminStatsResponseDto {
    return AdminStatsResponseDtoFromJSONTyped(json, false);
}

export function AdminStatsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminStatsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'users': UserMetricsDtoFromJSON(json['users']),
        'accounts': AccountMetricsDtoFromJSON(json['accounts']),
        'dataVolume': DataVolumeMetricsDtoFromJSON(json['dataVolume']),
    };
}

export function AdminStatsResponseDtoToJSON(json: any): AdminStatsResponseDto {
    return AdminStatsResponseDtoToJSONTyped(json, false);
}

export function AdminStatsResponseDtoToJSONTyped(value?: AdminStatsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'users': UserMetricsDtoToJSON(value['users']),
        'accounts': AccountMetricsDtoToJSON(value['accounts']),
        'dataVolume': DataVolumeMetricsDtoToJSON(value['dataVolume']),
    };
}

