/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminSendWeeklyStatsDto
 */
export interface AdminSendWeeklyStatsDto {
    /**
     * Target user ID whose weekly stats to send
     * @type {string}
     * @memberof AdminSendWeeklyStatsDto
     */
    userId: string;
}

/**
 * Check if a given object implements the AdminSendWeeklyStatsDto interface.
 */
export function instanceOfAdminSendWeeklyStatsDto(value: object): value is AdminSendWeeklyStatsDto {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function AdminSendWeeklyStatsDtoFromJSON(json: any): AdminSendWeeklyStatsDto {
    return AdminSendWeeklyStatsDtoFromJSONTyped(json, false);
}

export function AdminSendWeeklyStatsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminSendWeeklyStatsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
    };
}

export function AdminSendWeeklyStatsDtoToJSON(json: any): AdminSendWeeklyStatsDto {
    return AdminSendWeeklyStatsDtoToJSONTyped(json, false);
}

export function AdminSendWeeklyStatsDtoToJSONTyped(value?: AdminSendWeeklyStatsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
    };
}

