/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TopTootsCategoryDto } from './TopTootsCategoryDto';
import {
    TopTootsCategoryDtoFromJSON,
    TopTootsCategoryDtoFromJSONTyped,
    TopTootsCategoryDtoToJSON,
    TopTootsCategoryDtoToJSONTyped,
} from './TopTootsCategoryDto';

/**
 * 
 * @export
 * @interface AllTopTootsResponseDto
 */
export interface AllTopTootsResponseDto {
    /**
     * Top toots based on combined replies and boosts
     * @type {TopTootsCategoryDto}
     * @memberof AllTopTootsResponseDto
     */
    top: TopTootsCategoryDto;
    /**
     * Top toots ranked by replies
     * @type {TopTootsCategoryDto}
     * @memberof AllTopTootsResponseDto
     */
    topByReplies: TopTootsCategoryDto;
    /**
     * Top toots ranked by boosts (reblogs)
     * @type {TopTootsCategoryDto}
     * @memberof AllTopTootsResponseDto
     */
    topByBoosts: TopTootsCategoryDto;
    /**
     * Top toots ranked by favourites
     * @type {TopTootsCategoryDto}
     * @memberof AllTopTootsResponseDto
     */
    topByFavorites: TopTootsCategoryDto;
}

/**
 * Check if a given object implements the AllTopTootsResponseDto interface.
 */
export function instanceOfAllTopTootsResponseDto(value: object): value is AllTopTootsResponseDto {
    if (!('top' in value) || value['top'] === undefined) return false;
    if (!('topByReplies' in value) || value['topByReplies'] === undefined) return false;
    if (!('topByBoosts' in value) || value['topByBoosts'] === undefined) return false;
    if (!('topByFavorites' in value) || value['topByFavorites'] === undefined) return false;
    return true;
}

export function AllTopTootsResponseDtoFromJSON(json: any): AllTopTootsResponseDto {
    return AllTopTootsResponseDtoFromJSONTyped(json, false);
}

export function AllTopTootsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllTopTootsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'top': TopTootsCategoryDtoFromJSON(json['top']),
        'topByReplies': TopTootsCategoryDtoFromJSON(json['topByReplies']),
        'topByBoosts': TopTootsCategoryDtoFromJSON(json['topByBoosts']),
        'topByFavorites': TopTootsCategoryDtoFromJSON(json['topByFavorites']),
    };
}

export function AllTopTootsResponseDtoToJSON(json: any): AllTopTootsResponseDto {
    return AllTopTootsResponseDtoToJSONTyped(json, false);
}

export function AllTopTootsResponseDtoToJSONTyped(value?: AllTopTootsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'top': TopTootsCategoryDtoToJSON(value['top']),
        'topByReplies': TopTootsCategoryDtoToJSON(value['topByReplies']),
        'topByBoosts': TopTootsCategoryDtoToJSON(value['topByBoosts']),
        'topByFavorites': TopTootsCategoryDtoToJSON(value['topByFavorites']),
    };
}

