/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BoostsKpiDto
 */
export interface BoostsKpiDto {
    /**
     * Boosts in the current period
     * @type {number}
     * @memberof BoostsKpiDto
     */
    currentPeriod?: number;
    /**
     * Progress through the current period (0 to 1)
     * @type {number}
     * @memberof BoostsKpiDto
     */
    currentPeriodProgress?: number;
    /**
     * Boosts in the previous period
     * @type {number}
     * @memberof BoostsKpiDto
     */
    previousPeriod?: number;
    /**
     * Indicates if the current period is the full last period
     * @type {boolean}
     * @memberof BoostsKpiDto
     */
    isLastPeriod?: boolean;
    /**
     * Trend compared to the previous period (null if cannot be calculated)
     * @type {number}
     * @memberof BoostsKpiDto
     */
    trend?: number | null;
}

/**
 * Check if a given object implements the BoostsKpiDto interface.
 */
export function instanceOfBoostsKpiDto(value: object): value is BoostsKpiDto {
    return true;
}

export function BoostsKpiDtoFromJSON(json: any): BoostsKpiDto {
    return BoostsKpiDtoFromJSONTyped(json, false);
}

export function BoostsKpiDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoostsKpiDto {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPeriod': json['currentPeriod'] == null ? undefined : json['currentPeriod'],
        'currentPeriodProgress': json['currentPeriodProgress'] == null ? undefined : json['currentPeriodProgress'],
        'previousPeriod': json['previousPeriod'] == null ? undefined : json['previousPeriod'],
        'isLastPeriod': json['isLastPeriod'] == null ? undefined : json['isLastPeriod'],
        'trend': json['trend'] == null ? undefined : json['trend'],
    };
}

export function BoostsKpiDtoToJSON(json: any): BoostsKpiDto {
    return BoostsKpiDtoToJSONTyped(json, false);
}

export function BoostsKpiDtoToJSONTyped(value?: BoostsKpiDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currentPeriod': value['currentPeriod'],
        'currentPeriodProgress': value['currentPeriodProgress'],
        'previousPeriod': value['previousPeriod'],
        'isLastPeriod': value['isLastPeriod'],
        'trend': value['trend'],
    };
}

