/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChartDataPointDto
 */
export interface ChartDataPointDto {
    /**
     * Date for the data point
     * @type {string}
     * @memberof ChartDataPointDto
     */
    time: string;
    /**
     * Value for the data point
     * @type {number}
     * @memberof ChartDataPointDto
     */
    value: number | null;
}

/**
 * Check if a given object implements the ChartDataPointDto interface.
 */
export function instanceOfChartDataPointDto(value: object): value is ChartDataPointDto {
    if (!('time' in value) || value['time'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function ChartDataPointDtoFromJSON(json: any): ChartDataPointDto {
    return ChartDataPointDtoFromJSONTyped(json, false);
}

export function ChartDataPointDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChartDataPointDto {
    if (json == null) {
        return json;
    }
    return {
        
        'time': json['time'],
        'value': json['value'],
    };
}

export function ChartDataPointDtoToJSON(json: any): ChartDataPointDto {
    return ChartDataPointDtoToJSONTyped(json, false);
}

export function ChartDataPointDtoToJSONTyped(value?: ChartDataPointDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'time': value['time'],
        'value': value['value'],
    };
}

