/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CollectionSizesDto
 */
export interface CollectionSizesDto {
    /**
     * Number of user documents
     * @type {number}
     * @memberof CollectionSizesDto
     */
    users: number;
    /**
     * Number of account documents
     * @type {number}
     * @memberof CollectionSizesDto
     */
    accounts: number;
    /**
     * Number of toot documents
     * @type {number}
     * @memberof CollectionSizesDto
     */
    toots: number;
    /**
     * Number of daily account stats documents
     * @type {number}
     * @memberof CollectionSizesDto
     */
    dailyAccountStats: number;
    /**
     * Number of daily toot stats documents
     * @type {number}
     * @memberof CollectionSizesDto
     */
    dailyTootStats: number;
    /**
     * Number of refresh token documents
     * @type {number}
     * @memberof CollectionSizesDto
     */
    refreshTokens: number;
    /**
     * Number of mastodon app documents
     * @type {number}
     * @memberof CollectionSizesDto
     */
    mastodonApps: number;
    /**
     * Number of CLI job run documents
     * @type {number}
     * @memberof CollectionSizesDto
     */
    cliJobRuns: number;
}

/**
 * Check if a given object implements the CollectionSizesDto interface.
 */
export function instanceOfCollectionSizesDto(value: object): value is CollectionSizesDto {
    if (!('users' in value) || value['users'] === undefined) return false;
    if (!('accounts' in value) || value['accounts'] === undefined) return false;
    if (!('toots' in value) || value['toots'] === undefined) return false;
    if (!('dailyAccountStats' in value) || value['dailyAccountStats'] === undefined) return false;
    if (!('dailyTootStats' in value) || value['dailyTootStats'] === undefined) return false;
    if (!('refreshTokens' in value) || value['refreshTokens'] === undefined) return false;
    if (!('mastodonApps' in value) || value['mastodonApps'] === undefined) return false;
    if (!('cliJobRuns' in value) || value['cliJobRuns'] === undefined) return false;
    return true;
}

export function CollectionSizesDtoFromJSON(json: any): CollectionSizesDto {
    return CollectionSizesDtoFromJSONTyped(json, false);
}

export function CollectionSizesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionSizesDto {
    if (json == null) {
        return json;
    }
    return {
        
        'users': json['users'],
        'accounts': json['accounts'],
        'toots': json['toots'],
        'dailyAccountStats': json['dailyAccountStats'],
        'dailyTootStats': json['dailyTootStats'],
        'refreshTokens': json['refreshTokens'],
        'mastodonApps': json['mastodonApps'],
        'cliJobRuns': json['cliJobRuns'],
    };
}

export function CollectionSizesDtoToJSON(json: any): CollectionSizesDto {
    return CollectionSizesDtoToJSONTyped(json, false);
}

export function CollectionSizesDtoToJSONTyped(value?: CollectionSizesDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'users': value['users'],
        'accounts': value['accounts'],
        'toots': value['toots'],
        'dailyAccountStats': value['dailyAccountStats'],
        'dailyTootStats': value['dailyTootStats'],
        'refreshTokens': value['refreshTokens'],
        'mastodonApps': value['mastodonApps'],
        'cliJobRuns': value['cliJobRuns'],
    };
}

