/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConnectAccountResponseDto
 */
export interface ConnectAccountResponseDto {
    /**
     * The Mastodon OAuth authorization URL to redirect the user to.
     * @type {string}
     * @memberof ConnectAccountResponseDto
     */
    redirectUrl: string;
}

/**
 * Check if a given object implements the ConnectAccountResponseDto interface.
 */
export function instanceOfConnectAccountResponseDto(value: object): value is ConnectAccountResponseDto {
    if (!('redirectUrl' in value) || value['redirectUrl'] === undefined) return false;
    return true;
}

export function ConnectAccountResponseDtoFromJSON(json: any): ConnectAccountResponseDto {
    return ConnectAccountResponseDtoFromJSONTyped(json, false);
}

export function ConnectAccountResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectAccountResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'redirectUrl': json['redirectUrl'],
    };
}

export function ConnectAccountResponseDtoToJSON(json: any): ConnectAccountResponseDto {
    return ConnectAccountResponseDtoToJSONTyped(json, false);
}

export function ConnectAccountResponseDtoToJSONTyped(value?: ConnectAccountResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'redirectUrl': value['redirectUrl'],
    };
}

