/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAccountDto
 */
export interface CreateAccountDto {
    /**
     * A custom name for the account (e.g., for display in UI)
     * @type {string}
     * @memberof CreateAccountDto
     */
    name?: string;
    /**
     * The URL of the Mastodon server
     * @type {string}
     * @memberof CreateAccountDto
     */
    serverURL: string;
    /**
     * The timezone for the account
     * @type {string}
     * @memberof CreateAccountDto
     */
    timezone: string;
}

/**
 * Check if a given object implements the CreateAccountDto interface.
 */
export function instanceOfCreateAccountDto(value: object): value is CreateAccountDto {
    if (!('serverURL' in value) || value['serverURL'] === undefined) return false;
    if (!('timezone' in value) || value['timezone'] === undefined) return false;
    return true;
}

export function CreateAccountDtoFromJSON(json: any): CreateAccountDto {
    return CreateAccountDtoFromJSONTyped(json, false);
}

export function CreateAccountDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAccountDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'serverURL': json['serverURL'],
        'timezone': json['timezone'],
    };
}

export function CreateAccountDtoToJSON(json: any): CreateAccountDto {
    return CreateAccountDtoToJSONTyped(json, false);
}

export function CreateAccountDtoToJSONTyped(value?: CreateAccountDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'serverURL': value['serverURL'],
        'timezone': value['timezone'],
    };
}

