/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DailyCountDto
 */
export interface DailyCountDto {
    /**
     * Date in YYYY-MM-DD format
     * @type {string}
     * @memberof DailyCountDto
     */
    date: string;
    /**
     * Count for this date
     * @type {number}
     * @memberof DailyCountDto
     */
    count: number;
}

/**
 * Check if a given object implements the DailyCountDto interface.
 */
export function instanceOfDailyCountDto(value: object): value is DailyCountDto {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function DailyCountDtoFromJSON(json: any): DailyCountDto {
    return DailyCountDtoFromJSONTyped(json, false);
}

export function DailyCountDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DailyCountDto {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'],
        'count': json['count'],
    };
}

export function DailyCountDtoToJSON(json: any): DailyCountDto {
    return DailyCountDtoToJSONTyped(json, false);
}

export function DailyCountDtoToJSONTyped(value?: DailyCountDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'count': value['count'],
    };
}

