/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataFreshnessItemDto } from './DataFreshnessItemDto';
import {
    DataFreshnessItemDtoFromJSON,
    DataFreshnessItemDtoFromJSONTyped,
    DataFreshnessItemDtoToJSON,
    DataFreshnessItemDtoToJSONTyped,
} from './DataFreshnessItemDto';

/**
 * 
 * @export
 * @interface DataFreshnessDto
 */
export interface DataFreshnessDto {
    /**
     * Daily account stats freshness
     * @type {DataFreshnessItemDto}
     * @memberof DataFreshnessDto
     */
    dailyAccountStats: DataFreshnessItemDto;
    /**
     * Daily toot stats freshness
     * @type {DataFreshnessItemDto}
     * @memberof DataFreshnessDto
     */
    dailyTootStats: DataFreshnessItemDto;
    /**
     * Toots freshness
     * @type {DataFreshnessItemDto}
     * @memberof DataFreshnessDto
     */
    toots: DataFreshnessItemDto;
}

/**
 * Check if a given object implements the DataFreshnessDto interface.
 */
export function instanceOfDataFreshnessDto(value: object): value is DataFreshnessDto {
    if (!('dailyAccountStats' in value) || value['dailyAccountStats'] === undefined) return false;
    if (!('dailyTootStats' in value) || value['dailyTootStats'] === undefined) return false;
    if (!('toots' in value) || value['toots'] === undefined) return false;
    return true;
}

export function DataFreshnessDtoFromJSON(json: any): DataFreshnessDto {
    return DataFreshnessDtoFromJSONTyped(json, false);
}

export function DataFreshnessDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataFreshnessDto {
    if (json == null) {
        return json;
    }
    return {
        
        'dailyAccountStats': DataFreshnessItemDtoFromJSON(json['dailyAccountStats']),
        'dailyTootStats': DataFreshnessItemDtoFromJSON(json['dailyTootStats']),
        'toots': DataFreshnessItemDtoFromJSON(json['toots']),
    };
}

export function DataFreshnessDtoToJSON(json: any): DataFreshnessDto {
    return DataFreshnessDtoToJSONTyped(json, false);
}

export function DataFreshnessDtoToJSONTyped(value?: DataFreshnessDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dailyAccountStats': DataFreshnessItemDtoToJSON(value['dailyAccountStats']),
        'dailyTootStats': DataFreshnessItemDtoToJSON(value['dailyTootStats']),
        'toots': DataFreshnessItemDtoToJSON(value['toots']),
    };
}

