/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataFreshnessItemDto
 */
export interface DataFreshnessItemDto {
    /**
     * Latest date of data
     * @type {string}
     * @memberof DataFreshnessItemDto
     */
    latestDate: string | null;
    /**
     * Latest fetchedAt timestamp
     * @type {string}
     * @memberof DataFreshnessItemDto
     */
    latestFetchedAt: string | null;
    /**
     * Whether the data is stale (> 2 days old)
     * @type {boolean}
     * @memberof DataFreshnessItemDto
     */
    isStale: boolean;
}

/**
 * Check if a given object implements the DataFreshnessItemDto interface.
 */
export function instanceOfDataFreshnessItemDto(value: object): value is DataFreshnessItemDto {
    if (!('latestDate' in value) || value['latestDate'] === undefined) return false;
    if (!('latestFetchedAt' in value) || value['latestFetchedAt'] === undefined) return false;
    if (!('isStale' in value) || value['isStale'] === undefined) return false;
    return true;
}

export function DataFreshnessItemDtoFromJSON(json: any): DataFreshnessItemDto {
    return DataFreshnessItemDtoFromJSONTyped(json, false);
}

export function DataFreshnessItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataFreshnessItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'latestDate': json['latestDate'],
        'latestFetchedAt': json['latestFetchedAt'],
        'isStale': json['isStale'],
    };
}

export function DataFreshnessItemDtoToJSON(json: any): DataFreshnessItemDto {
    return DataFreshnessItemDtoToJSONTyped(json, false);
}

export function DataFreshnessItemDtoToJSONTyped(value?: DataFreshnessItemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'latestDate': value['latestDate'],
        'latestFetchedAt': value['latestFetchedAt'],
        'isStale': value['isStale'],
    };
}

