/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataVolumeMetricsDto
 */
export interface DataVolumeMetricsDto {
    /**
     * Total number of tracked toots
     * @type {number}
     * @memberof DataVolumeMetricsDto
     */
    totalToots: number;
    /**
     * Total number of daily account stats records
     * @type {number}
     * @memberof DataVolumeMetricsDto
     */
    totalDailyAccountStats: number;
    /**
     * Total number of daily toot stats records
     * @type {number}
     * @memberof DataVolumeMetricsDto
     */
    totalDailyTootStats: number;
}

/**
 * Check if a given object implements the DataVolumeMetricsDto interface.
 */
export function instanceOfDataVolumeMetricsDto(value: object): value is DataVolumeMetricsDto {
    if (!('totalToots' in value) || value['totalToots'] === undefined) return false;
    if (!('totalDailyAccountStats' in value) || value['totalDailyAccountStats'] === undefined) return false;
    if (!('totalDailyTootStats' in value) || value['totalDailyTootStats'] === undefined) return false;
    return true;
}

export function DataVolumeMetricsDtoFromJSON(json: any): DataVolumeMetricsDto {
    return DataVolumeMetricsDtoFromJSONTyped(json, false);
}

export function DataVolumeMetricsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataVolumeMetricsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'totalToots': json['totalToots'],
        'totalDailyAccountStats': json['totalDailyAccountStats'],
        'totalDailyTootStats': json['totalDailyTootStats'],
    };
}

export function DataVolumeMetricsDtoToJSON(json: any): DataVolumeMetricsDto {
    return DataVolumeMetricsDtoToJSONTyped(json, false);
}

export function DataVolumeMetricsDtoToJSONTyped(value?: DataVolumeMetricsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalToots': value['totalToots'],
        'totalDailyAccountStats': value['totalDailyAccountStats'],
        'totalDailyTootStats': value['totalDailyTootStats'],
    };
}

