/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FavoritesKpiDto
 */
export interface FavoritesKpiDto {
    /**
     * Favorites in the current period
     * @type {number}
     * @memberof FavoritesKpiDto
     */
    currentPeriod?: number;
    /**
     * Progress through the current period (0 to 1)
     * @type {number}
     * @memberof FavoritesKpiDto
     */
    currentPeriodProgress?: number;
    /**
     * Favorites in the previous period
     * @type {number}
     * @memberof FavoritesKpiDto
     */
    previousPeriod?: number;
    /**
     * Indicates if the current period is the full last period
     * @type {boolean}
     * @memberof FavoritesKpiDto
     */
    isLastPeriod?: boolean;
    /**
     * Trend compared to the previous period
     * @type {number}
     * @memberof FavoritesKpiDto
     */
    trend?: number;
}

/**
 * Check if a given object implements the FavoritesKpiDto interface.
 */
export function instanceOfFavoritesKpiDto(value: object): value is FavoritesKpiDto {
    return true;
}

export function FavoritesKpiDtoFromJSON(json: any): FavoritesKpiDto {
    return FavoritesKpiDtoFromJSONTyped(json, false);
}

export function FavoritesKpiDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FavoritesKpiDto {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPeriod': json['currentPeriod'] == null ? undefined : json['currentPeriod'],
        'currentPeriodProgress': json['currentPeriodProgress'] == null ? undefined : json['currentPeriodProgress'],
        'previousPeriod': json['previousPeriod'] == null ? undefined : json['previousPeriod'],
        'isLastPeriod': json['isLastPeriod'] == null ? undefined : json['isLastPeriod'],
        'trend': json['trend'] == null ? undefined : json['trend'],
    };
}

export function FavoritesKpiDtoToJSON(json: any): FavoritesKpiDto {
    return FavoritesKpiDtoToJSONTyped(json, false);
}

export function FavoritesKpiDtoToJSONTyped(value?: FavoritesKpiDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currentPeriod': value['currentPeriod'],
        'currentPeriodProgress': value['currentPeriodProgress'],
        'previousPeriod': value['previousPeriod'],
        'isLastPeriod': value['isLastPeriod'],
        'trend': value['trend'],
    };
}

