/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FirstStatsMailDto
 */
export interface FirstStatsMailDto {
    /**
     * User ID
     * @type {string}
     * @memberof FirstStatsMailDto
     */
    userID: string;
    /**
     * Array of Account IDs for which first stats are available
     * @type {Array<string>}
     * @memberof FirstStatsMailDto
     */
    accounts: Array<string>;
}

/**
 * Check if a given object implements the FirstStatsMailDto interface.
 */
export function instanceOfFirstStatsMailDto(value: object): value is FirstStatsMailDto {
    if (!('userID' in value) || value['userID'] === undefined) return false;
    if (!('accounts' in value) || value['accounts'] === undefined) return false;
    return true;
}

export function FirstStatsMailDtoFromJSON(json: any): FirstStatsMailDto {
    return FirstStatsMailDtoFromJSONTyped(json, false);
}

export function FirstStatsMailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FirstStatsMailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userID': json['userID'],
        'accounts': json['accounts'],
    };
}

export function FirstStatsMailDtoToJSON(json: any): FirstStatsMailDto {
    return FirstStatsMailDtoToJSONTyped(json, false);
}

export function FirstStatsMailDtoToJSONTyped(value?: FirstStatsMailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userID': value['userID'],
        'accounts': value['accounts'],
    };
}

