/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HashtagOverTimeDto
 */
export interface HashtagOverTimeDto {
    /**
     * 
     * @type {Array<string>}
     * @memberof HashtagOverTimeDto
     */
    hashtags: Array<string>;
    /**
     * 
     * @type {Array<object>}
     * @memberof HashtagOverTimeDto
     */
    data: Array<object>;
}

/**
 * Check if a given object implements the HashtagOverTimeDto interface.
 */
export function instanceOfHashtagOverTimeDto(value: object): value is HashtagOverTimeDto {
    if (!('hashtags' in value) || value['hashtags'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function HashtagOverTimeDtoFromJSON(json: any): HashtagOverTimeDto {
    return HashtagOverTimeDtoFromJSONTyped(json, false);
}

export function HashtagOverTimeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HashtagOverTimeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'hashtags': json['hashtags'],
        'data': json['data'],
    };
}

export function HashtagOverTimeDtoToJSON(json: any): HashtagOverTimeDto {
    return HashtagOverTimeDtoToJSONTyped(json, false);
}

export function HashtagOverTimeDtoToJSONTyped(value?: HashtagOverTimeDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hashtags': value['hashtags'],
        'data': value['data'],
    };
}

