/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type HashtagOverTimeDtoDataInnerValue
 * 
 * @export
 */
export type HashtagOverTimeDtoDataInnerValue = number | string;

export function HashtagOverTimeDtoDataInnerValueFromJSON(json: any): HashtagOverTimeDtoDataInnerValue {
    return HashtagOverTimeDtoDataInnerValueFromJSONTyped(json, false);
}

export function HashtagOverTimeDtoDataInnerValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): HashtagOverTimeDtoDataInnerValue {
    if (json == null) {
        return json;
    }

    return {} as any;
}

export function HashtagOverTimeDtoDataInnerValueToJSON(json: any): any {
    return HashtagOverTimeDtoDataInnerValueToJSONTyped(json, false);
}

export function HashtagOverTimeDtoDataInnerValueToJSONTyped(value?: HashtagOverTimeDtoDataInnerValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {};
}

