/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HashtagTopDto
 */
export interface HashtagTopDto {
    /**
     * 
     * @type {string}
     * @memberof HashtagTopDto
     */
    hashtag: string;
    /**
     * 
     * @type {number}
     * @memberof HashtagTopDto
     */
    tootCount: number;
    /**
     * 
     * @type {number}
     * @memberof HashtagTopDto
     */
    repliesCount: number;
    /**
     * 
     * @type {number}
     * @memberof HashtagTopDto
     */
    reblogsCount: number;
    /**
     * 
     * @type {number}
     * @memberof HashtagTopDto
     */
    favouritesCount: number;
}

/**
 * Check if a given object implements the HashtagTopDto interface.
 */
export function instanceOfHashtagTopDto(value: object): value is HashtagTopDto {
    if (!('hashtag' in value) || value['hashtag'] === undefined) return false;
    if (!('tootCount' in value) || value['tootCount'] === undefined) return false;
    if (!('repliesCount' in value) || value['repliesCount'] === undefined) return false;
    if (!('reblogsCount' in value) || value['reblogsCount'] === undefined) return false;
    if (!('favouritesCount' in value) || value['favouritesCount'] === undefined) return false;
    return true;
}

export function HashtagTopDtoFromJSON(json: any): HashtagTopDto {
    return HashtagTopDtoFromJSONTyped(json, false);
}

export function HashtagTopDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HashtagTopDto {
    if (json == null) {
        return json;
    }
    return {
        
        'hashtag': json['hashtag'],
        'tootCount': json['tootCount'],
        'repliesCount': json['repliesCount'],
        'reblogsCount': json['reblogsCount'],
        'favouritesCount': json['favouritesCount'],
    };
}

export function HashtagTopDtoToJSON(json: any): HashtagTopDto {
    return HashtagTopDtoToJSONTyped(json, false);
}

export function HashtagTopDtoToJSONTyped(value?: HashtagTopDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hashtag': value['hashtag'],
        'tootCount': value['tootCount'],
        'repliesCount': value['repliesCount'],
        'reblogsCount': value['reblogsCount'],
        'favouritesCount': value['favouritesCount'],
    };
}

