/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HashtagEngagementDto
 */
export interface HashtagEngagementDto {
    /**
     * 
     * @type {string}
     * @memberof HashtagEngagementDto
     */
    hashtag: string;
    /**
     * 
     * @type {number}
     * @memberof HashtagEngagementDto
     */
    tootCount: number;
    /**
     * 
     * @type {number}
     * @memberof HashtagEngagementDto
     */
    totalEngagement: number;
    /**
     * 
     * @type {number}
     * @memberof HashtagEngagementDto
     */
    avgEngagementPerToot: number;
    /**
     * 
     * @type {number}
     * @memberof HashtagEngagementDto
     */
    repliesCount: number;
    /**
     * 
     * @type {number}
     * @memberof HashtagEngagementDto
     */
    reblogsCount: number;
    /**
     * 
     * @type {number}
     * @memberof HashtagEngagementDto
     */
    favouritesCount: number;
}

/**
 * Check if a given object implements the HashtagEngagementDto interface.
 */
export function instanceOfHashtagEngagementDto(value: object): value is HashtagEngagementDto {
    if (!('hashtag' in value) || value['hashtag'] === undefined) return false;
    if (!('tootCount' in value) || value['tootCount'] === undefined) return false;
    if (!('totalEngagement' in value) || value['totalEngagement'] === undefined) return false;
    if (!('avgEngagementPerToot' in value) || value['avgEngagementPerToot'] === undefined) return false;
    if (!('repliesCount' in value) || value['repliesCount'] === undefined) return false;
    if (!('reblogsCount' in value) || value['reblogsCount'] === undefined) return false;
    if (!('favouritesCount' in value) || value['favouritesCount'] === undefined) return false;
    return true;
}

export function HashtagEngagementDtoFromJSON(json: any): HashtagEngagementDto {
    return HashtagEngagementDtoFromJSONTyped(json, false);
}

export function HashtagEngagementDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HashtagEngagementDto {
    if (json == null) {
        return json;
    }
    return {
        
        'hashtag': json['hashtag'],
        'tootCount': json['tootCount'],
        'totalEngagement': json['totalEngagement'],
        'avgEngagementPerToot': json['avgEngagementPerToot'],
        'repliesCount': json['repliesCount'],
        'reblogsCount': json['reblogsCount'],
        'favouritesCount': json['favouritesCount'],
    };
}

export function HashtagEngagementDtoToJSON(json: any): HashtagEngagementDto {
    return HashtagEngagementDtoToJSONTyped(json, false);
}

export function HashtagEngagementDtoToJSONTyped(value?: HashtagEngagementDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hashtag': value['hashtag'],
        'tootCount': value['tootCount'],
        'totalEngagement': value['totalEngagement'],
        'avgEngagementPerToot': value['avgEngagementPerToot'],
        'repliesCount': value['repliesCount'],
        'reblogsCount': value['reblogsCount'],
        'favouritesCount': value['favouritesCount'],
    };
}

