/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IncompleteAccountDto
 */
export interface IncompleteAccountDto {
    /**
     * Account ID
     * @type {string}
     * @memberof IncompleteAccountDto
     */
    accountId: string;
    /**
     * Mastodon account name (may not be set yet)
     * @type {string}
     * @memberof IncompleteAccountDto
     */
    accountName: string | null;
    /**
     * Mastodon server URL
     * @type {string}
     * @memberof IncompleteAccountDto
     */
    serverURL: string;
    /**
     * Account owner email
     * @type {string}
     * @memberof IncompleteAccountDto
     */
    ownerEmail: string;
    /**
     * Account creation date
     * @type {string}
     * @memberof IncompleteAccountDto
     */
    createdDate: string;
    /**
     * Days since account was created
     * @type {number}
     * @memberof IncompleteAccountDto
     */
    daysSinceCreation: number;
}

/**
 * Check if a given object implements the IncompleteAccountDto interface.
 */
export function instanceOfIncompleteAccountDto(value: object): value is IncompleteAccountDto {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('accountName' in value) || value['accountName'] === undefined) return false;
    if (!('serverURL' in value) || value['serverURL'] === undefined) return false;
    if (!('ownerEmail' in value) || value['ownerEmail'] === undefined) return false;
    if (!('createdDate' in value) || value['createdDate'] === undefined) return false;
    if (!('daysSinceCreation' in value) || value['daysSinceCreation'] === undefined) return false;
    return true;
}

export function IncompleteAccountDtoFromJSON(json: any): IncompleteAccountDto {
    return IncompleteAccountDtoFromJSONTyped(json, false);
}

export function IncompleteAccountDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncompleteAccountDto {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'accountName': json['accountName'],
        'serverURL': json['serverURL'],
        'ownerEmail': json['ownerEmail'],
        'createdDate': json['createdDate'],
        'daysSinceCreation': json['daysSinceCreation'],
    };
}

export function IncompleteAccountDtoToJSON(json: any): IncompleteAccountDto {
    return IncompleteAccountDtoToJSONTyped(json, false);
}

export function IncompleteAccountDtoToJSONTyped(value?: IncompleteAccountDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'accountName': value['accountName'],
        'serverURL': value['serverURL'],
        'ownerEmail': value['ownerEmail'],
        'createdDate': value['createdDate'],
        'daysSinceCreation': value['daysSinceCreation'],
    };
}

