/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobStatusDto
 */
export interface JobStatusDto {
    /**
     * Job name
     * @type {string}
     * @memberof JobStatusDto
     */
    jobName: string;
    /**
     * When the job last started
     * @type {string}
     * @memberof JobStatusDto
     */
    lastStartedAt: string;
    /**
     * When the job last completed
     * @type {string}
     * @memberof JobStatusDto
     */
    lastCompletedAt: string | null;
    /**
     * Last job status (running, success, failure, stuck)
     * @type {string}
     * @memberof JobStatusDto
     */
    lastStatus: string;
    /**
     * Duration of last run in ms
     * @type {number}
     * @memberof JobStatusDto
     */
    lastDurationMs: number | null;
    /**
     * Records processed in last run
     * @type {number}
     * @memberof JobStatusDto
     */
    lastRecordsProcessed: number | null;
    /**
     * Error message from last run
     * @type {string}
     * @memberof JobStatusDto
     */
    lastErrorMessage: string | null;
    /**
     * Whether the job is overdue (last run > 24h ago)
     * @type {boolean}
     * @memberof JobStatusDto
     */
    isOverdue: boolean;
}

/**
 * Check if a given object implements the JobStatusDto interface.
 */
export function instanceOfJobStatusDto(value: object): value is JobStatusDto {
    if (!('jobName' in value) || value['jobName'] === undefined) return false;
    if (!('lastStartedAt' in value) || value['lastStartedAt'] === undefined) return false;
    if (!('lastCompletedAt' in value) || value['lastCompletedAt'] === undefined) return false;
    if (!('lastStatus' in value) || value['lastStatus'] === undefined) return false;
    if (!('lastDurationMs' in value) || value['lastDurationMs'] === undefined) return false;
    if (!('lastRecordsProcessed' in value) || value['lastRecordsProcessed'] === undefined) return false;
    if (!('lastErrorMessage' in value) || value['lastErrorMessage'] === undefined) return false;
    if (!('isOverdue' in value) || value['isOverdue'] === undefined) return false;
    return true;
}

export function JobStatusDtoFromJSON(json: any): JobStatusDto {
    return JobStatusDtoFromJSONTyped(json, false);
}

export function JobStatusDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobStatusDto {
    if (json == null) {
        return json;
    }
    return {
        
        'jobName': json['jobName'],
        'lastStartedAt': json['lastStartedAt'],
        'lastCompletedAt': json['lastCompletedAt'],
        'lastStatus': json['lastStatus'],
        'lastDurationMs': json['lastDurationMs'],
        'lastRecordsProcessed': json['lastRecordsProcessed'],
        'lastErrorMessage': json['lastErrorMessage'],
        'isOverdue': json['isOverdue'],
    };
}

export function JobStatusDtoToJSON(json: any): JobStatusDto {
    return JobStatusDtoToJSONTyped(json, false);
}

export function JobStatusDtoToJSONTyped(value?: JobStatusDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jobName': value['jobName'],
        'lastStartedAt': value['lastStartedAt'],
        'lastCompletedAt': value['lastCompletedAt'],
        'lastStatus': value['lastStatus'],
        'lastDurationMs': value['lastDurationMs'],
        'lastRecordsProcessed': value['lastRecordsProcessed'],
        'lastErrorMessage': value['lastErrorMessage'],
        'isOverdue': value['isOverdue'],
    };
}

