/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginActivityDto
 */
export interface LoginActivityDto {
    /**
     * Users who logged in during the last 7 days
     * @type {number}
     * @memberof LoginActivityDto
     */
    last7Days: number;
    /**
     * Users who logged in during the last 30 days
     * @type {number}
     * @memberof LoginActivityDto
     */
    last30Days: number;
    /**
     * Users who logged in during the last 90 days
     * @type {number}
     * @memberof LoginActivityDto
     */
    last90Days: number;
}

/**
 * Check if a given object implements the LoginActivityDto interface.
 */
export function instanceOfLoginActivityDto(value: object): value is LoginActivityDto {
    if (!('last7Days' in value) || value['last7Days'] === undefined) return false;
    if (!('last30Days' in value) || value['last30Days'] === undefined) return false;
    if (!('last90Days' in value) || value['last90Days'] === undefined) return false;
    return true;
}

export function LoginActivityDtoFromJSON(json: any): LoginActivityDto {
    return LoginActivityDtoFromJSONTyped(json, false);
}

export function LoginActivityDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginActivityDto {
    if (json == null) {
        return json;
    }
    return {
        
        'last7Days': json['last7Days'],
        'last30Days': json['last30Days'],
        'last90Days': json['last90Days'],
    };
}

export function LoginActivityDtoToJSON(json: any): LoginActivityDto {
    return LoginActivityDtoToJSONTyped(json, false);
}

export function LoginActivityDtoToJSONTyped(value?: LoginActivityDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'last7Days': value['last7Days'],
        'last30Days': value['last30Days'],
        'last90Days': value['last90Days'],
    };
}

