/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ManageSubscriptionDto
 */
export interface ManageSubscriptionDto {
    /**
     * User ID
     * @type {string}
     * @memberof ManageSubscriptionDto
     */
    u: string;
    /**
     * User email
     * @type {string}
     * @memberof ManageSubscriptionDto
     */
    e: string;
}

/**
 * Check if a given object implements the ManageSubscriptionDto interface.
 */
export function instanceOfManageSubscriptionDto(value: object): value is ManageSubscriptionDto {
    if (!('u' in value) || value['u'] === undefined) return false;
    if (!('e' in value) || value['e'] === undefined) return false;
    return true;
}

export function ManageSubscriptionDtoFromJSON(json: any): ManageSubscriptionDto {
    return ManageSubscriptionDtoFromJSONTyped(json, false);
}

export function ManageSubscriptionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManageSubscriptionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'u': json['u'],
        'e': json['e'],
    };
}

export function ManageSubscriptionDtoToJSON(json: any): ManageSubscriptionDto {
    return ManageSubscriptionDtoToJSONTyped(json, false);
}

export function ManageSubscriptionDtoToJSONTyped(value?: ManageSubscriptionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'u': value['u'],
        'e': value['e'],
    };
}

