/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OldAccountMailDto
 */
export interface OldAccountMailDto {
    /**
     * User ID for whom to send the old account warning
     * @type {string}
     * @memberof OldAccountMailDto
     */
    userID: string;
}

/**
 * Check if a given object implements the OldAccountMailDto interface.
 */
export function instanceOfOldAccountMailDto(value: object): value is OldAccountMailDto {
    if (!('userID' in value) || value['userID'] === undefined) return false;
    return true;
}

export function OldAccountMailDtoFromJSON(json: any): OldAccountMailDto {
    return OldAccountMailDtoFromJSONTyped(json, false);
}

export function OldAccountMailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OldAccountMailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userID': json['userID'],
    };
}

export function OldAccountMailDtoToJSON(json: any): OldAccountMailDto {
    return OldAccountMailDtoToJSONTyped(json, false);
}

export function OldAccountMailDtoToJSONTyped(value?: OldAccountMailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userID': value['userID'],
    };
}

