/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecentFailureDto
 */
export interface RecentFailureDto {
    /**
     * Job name
     * @type {string}
     * @memberof RecentFailureDto
     */
    jobName: string;
    /**
     * When the job started
     * @type {string}
     * @memberof RecentFailureDto
     */
    startedAt: string;
    /**
     * Error message
     * @type {string}
     * @memberof RecentFailureDto
     */
    errorMessage: string | null;
}

/**
 * Check if a given object implements the RecentFailureDto interface.
 */
export function instanceOfRecentFailureDto(value: object): value is RecentFailureDto {
    if (!('jobName' in value) || value['jobName'] === undefined) return false;
    if (!('startedAt' in value) || value['startedAt'] === undefined) return false;
    if (!('errorMessage' in value) || value['errorMessage'] === undefined) return false;
    return true;
}

export function RecentFailureDtoFromJSON(json: any): RecentFailureDto {
    return RecentFailureDtoFromJSONTyped(json, false);
}

export function RecentFailureDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecentFailureDto {
    if (json == null) {
        return json;
    }
    return {
        
        'jobName': json['jobName'],
        'startedAt': json['startedAt'],
        'errorMessage': json['errorMessage'],
    };
}

export function RecentFailureDtoToJSON(json: any): RecentFailureDto {
    return RecentFailureDtoToJSONTyped(json, false);
}

export function RecentFailureDtoToJSONTyped(value?: RecentFailureDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jobName': value['jobName'],
        'startedAt': value['startedAt'],
        'errorMessage': value['errorMessage'],
    };
}

