/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecipientCountResponseDto
 */
export interface RecipientCountResponseDto {
    /**
     * Number of recipients in the selected group
     * @type {number}
     * @memberof RecipientCountResponseDto
     */
    count: number;
}

/**
 * Check if a given object implements the RecipientCountResponseDto interface.
 */
export function instanceOfRecipientCountResponseDto(value: object): value is RecipientCountResponseDto {
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function RecipientCountResponseDtoFromJSON(json: any): RecipientCountResponseDto {
    return RecipientCountResponseDtoFromJSONTyped(json, false);
}

export function RecipientCountResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipientCountResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
    };
}

export function RecipientCountResponseDtoToJSON(json: any): RecipientCountResponseDto {
    return RecipientCountResponseDtoToJSONTyped(json, false);
}

export function RecipientCountResponseDtoToJSONTyped(value?: RecipientCountResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
    };
}

