/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefreshTokenDto
 */
export interface RefreshTokenDto {
    /**
     * The refresh token used to obtain a new access token
     * @type {string}
     * @memberof RefreshTokenDto
     */
    refreshToken: string;
}

/**
 * Check if a given object implements the RefreshTokenDto interface.
 */
export function instanceOfRefreshTokenDto(value: object): value is RefreshTokenDto {
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    return true;
}

export function RefreshTokenDtoFromJSON(json: any): RefreshTokenDto {
    return RefreshTokenDtoFromJSONTyped(json, false);
}

export function RefreshTokenDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshTokenDto {
    if (json == null) {
        return json;
    }
    return {
        
        'refreshToken': json['refreshToken'],
    };
}

export function RefreshTokenDtoToJSON(json: any): RefreshTokenDto {
    return RefreshTokenDtoToJSONTyped(json, false);
}

export function RefreshTokenDtoToJSONTyped(value?: RefreshTokenDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'refreshToken': value['refreshToken'],
    };
}

