/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DailyCountDto } from './DailyCountDto';
import {
    DailyCountDtoFromJSON,
    DailyCountDtoFromJSONTyped,
    DailyCountDtoToJSON,
    DailyCountDtoToJSONTyped,
} from './DailyCountDto';

/**
 * 
 * @export
 * @interface RegistrationTrendDto
 */
export interface RegistrationTrendDto {
    /**
     * Number of registrations in the last 30 days
     * @type {number}
     * @memberof RegistrationTrendDto
     */
    last30DaysCount: number;
    /**
     * Daily registration counts for the last 30 days
     * @type {Array<DailyCountDto>}
     * @memberof RegistrationTrendDto
     */
    dailyBreakdown: Array<DailyCountDto>;
}

/**
 * Check if a given object implements the RegistrationTrendDto interface.
 */
export function instanceOfRegistrationTrendDto(value: object): value is RegistrationTrendDto {
    if (!('last30DaysCount' in value) || value['last30DaysCount'] === undefined) return false;
    if (!('dailyBreakdown' in value) || value['dailyBreakdown'] === undefined) return false;
    return true;
}

export function RegistrationTrendDtoFromJSON(json: any): RegistrationTrendDto {
    return RegistrationTrendDtoFromJSONTyped(json, false);
}

export function RegistrationTrendDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrationTrendDto {
    if (json == null) {
        return json;
    }
    return {
        
        'last30DaysCount': json['last30DaysCount'],
        'dailyBreakdown': ((json['dailyBreakdown'] as Array<any>).map(DailyCountDtoFromJSON)),
    };
}

export function RegistrationTrendDtoToJSON(json: any): RegistrationTrendDto {
    return RegistrationTrendDtoToJSONTyped(json, false);
}

export function RegistrationTrendDtoToJSONTyped(value?: RegistrationTrendDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'last30DaysCount': value['last30DaysCount'],
        'dailyBreakdown': ((value['dailyBreakdown'] as Array<any>).map(DailyCountDtoToJSON)),
    };
}

