/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterUserDto
 */
export interface RegisterUserDto {
    /**
     * User email address
     * @type {string}
     * @memberof RegisterUserDto
     */
    email: string;
    /**
     * User password (at least 8 characters)
     * @type {string}
     * @memberof RegisterUserDto
     */
    password: string;
    /**
     * Server URL user signed up with (optional)
     * @type {string}
     * @memberof RegisterUserDto
     */
    serverURLOnSignUp?: string;
    /**
     * User timezone (optional)
     * @type {string}
     * @memberof RegisterUserDto
     */
    timezone?: string;
}

/**
 * Check if a given object implements the RegisterUserDto interface.
 */
export function instanceOfRegisterUserDto(value: object): value is RegisterUserDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function RegisterUserDtoFromJSON(json: any): RegisterUserDto {
    return RegisterUserDtoFromJSONTyped(json, false);
}

export function RegisterUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'serverURLOnSignUp': json['serverURLOnSignUp'] == null ? undefined : json['serverURLOnSignUp'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
    };
}

export function RegisterUserDtoToJSON(json: any): RegisterUserDto {
    return RegisterUserDtoToJSONTyped(json, false);
}

export function RegisterUserDtoToJSONTyped(value?: RegisterUserDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'serverURLOnSignUp': value['serverURLOnSignUp'],
        'timezone': value['timezone'],
    };
}

