/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RepliedTootDto
 */
export interface RepliedTootDto {
    /**
     * Toot ID
     * @type {string}
     * @memberof RepliedTootDto
     */
    id: string;
    /**
     * Toot content (HTML)
     * @type {string}
     * @memberof RepliedTootDto
     */
    content: string;
    /**
     * URL of the toot
     * @type {string}
     * @memberof RepliedTootDto
     */
    url: string;
    /**
     * Number of boosts (reblogs)
     * @type {number}
     * @memberof RepliedTootDto
     */
    reblogsCount: number;
    /**
     * Number of replies
     * @type {number}
     * @memberof RepliedTootDto
     */
    repliesCount: number;
    /**
     * Number of favorites
     * @type {number}
     * @memberof RepliedTootDto
     */
    favouritesCount: number;
    /**
     * Creation date of the toot
     * @type {Date}
     * @memberof RepliedTootDto
     */
    createdAt: Date;
    /**
     * Calculated rank for sorting
     * @type {number}
     * @memberof RepliedTootDto
     */
    rank?: number;
}

/**
 * Check if a given object implements the RepliedTootDto interface.
 */
export function instanceOfRepliedTootDto(value: object): value is RepliedTootDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('reblogsCount' in value) || value['reblogsCount'] === undefined) return false;
    if (!('repliesCount' in value) || value['repliesCount'] === undefined) return false;
    if (!('favouritesCount' in value) || value['favouritesCount'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function RepliedTootDtoFromJSON(json: any): RepliedTootDto {
    return RepliedTootDtoFromJSONTyped(json, false);
}

export function RepliedTootDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepliedTootDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'content': json['content'],
        'url': json['url'],
        'reblogsCount': json['reblogsCount'],
        'repliesCount': json['repliesCount'],
        'favouritesCount': json['favouritesCount'],
        'createdAt': (new Date(json['createdAt'])),
        'rank': json['rank'] == null ? undefined : json['rank'],
    };
}

export function RepliedTootDtoToJSON(json: any): RepliedTootDto {
    return RepliedTootDtoToJSONTyped(json, false);
}

export function RepliedTootDtoToJSONTyped(value?: RepliedTootDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'content': value['content'],
        'url': value['url'],
        'reblogsCount': value['reblogsCount'],
        'repliesCount': value['repliesCount'],
        'favouritesCount': value['favouritesCount'],
        'createdAt': ((value['createdAt']).toISOString()),
        'rank': value['rank'],
    };
}

