/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RepliesKpiDto
 */
export interface RepliesKpiDto {
    /**
     * Replies in the current period
     * @type {number}
     * @memberof RepliesKpiDto
     */
    currentPeriod?: number;
    /**
     * Progress through the current period (0 to 1)
     * @type {number}
     * @memberof RepliesKpiDto
     */
    currentPeriodProgress?: number;
    /**
     * Replies in the previous period
     * @type {number}
     * @memberof RepliesKpiDto
     */
    previousPeriod?: number;
    /**
     * Indicates if the current period is the full last period
     * @type {boolean}
     * @memberof RepliesKpiDto
     */
    isLastPeriod?: boolean;
    /**
     * Trend compared to the previous period
     * @type {number}
     * @memberof RepliesKpiDto
     */
    trend?: number;
}

/**
 * Check if a given object implements the RepliesKpiDto interface.
 */
export function instanceOfRepliesKpiDto(value: object): value is RepliesKpiDto {
    return true;
}

export function RepliesKpiDtoFromJSON(json: any): RepliesKpiDto {
    return RepliesKpiDtoFromJSONTyped(json, false);
}

export function RepliesKpiDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepliesKpiDto {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPeriod': json['currentPeriod'] == null ? undefined : json['currentPeriod'],
        'currentPeriodProgress': json['currentPeriodProgress'] == null ? undefined : json['currentPeriodProgress'],
        'previousPeriod': json['previousPeriod'] == null ? undefined : json['previousPeriod'],
        'isLastPeriod': json['isLastPeriod'] == null ? undefined : json['isLastPeriod'],
        'trend': json['trend'] == null ? undefined : json['trend'],
    };
}

export function RepliesKpiDtoToJSON(json: any): RepliesKpiDto {
    return RepliesKpiDtoToJSONTyped(json, false);
}

export function RepliesKpiDtoToJSONTyped(value?: RepliesKpiDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currentPeriod': value['currentPeriod'],
        'currentPeriodProgress': value['currentPeriodProgress'],
        'previousPeriod': value['previousPeriod'],
        'isLastPeriod': value['isLastPeriod'],
        'trend': value['trend'],
    };
}

