/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoleBreakdownDto
 */
export interface RoleBreakdownDto {
    /**
     * Number of admin users
     * @type {number}
     * @memberof RoleBreakdownDto
     */
    admin: number;
    /**
     * Number of account owner users
     * @type {number}
     * @memberof RoleBreakdownDto
     */
    accountOwner: number;
}

/**
 * Check if a given object implements the RoleBreakdownDto interface.
 */
export function instanceOfRoleBreakdownDto(value: object): value is RoleBreakdownDto {
    if (!('admin' in value) || value['admin'] === undefined) return false;
    if (!('accountOwner' in value) || value['accountOwner'] === undefined) return false;
    return true;
}

export function RoleBreakdownDtoFromJSON(json: any): RoleBreakdownDto {
    return RoleBreakdownDtoFromJSONTyped(json, false);
}

export function RoleBreakdownDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleBreakdownDto {
    if (json == null) {
        return json;
    }
    return {
        
        'admin': json['admin'],
        'accountOwner': json['accountOwner'],
    };
}

export function RoleBreakdownDtoToJSON(json: any): RoleBreakdownDto {
    return RoleBreakdownDtoToJSONTyped(json, false);
}

export function RoleBreakdownDtoToJSONTyped(value?: RoleBreakdownDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'admin': value['admin'],
        'accountOwner': value['accountOwner'],
    };
}

