/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendEmailDto
 */
export interface SendEmailDto {
    /**
     * Recipient group: 'all' or 'active' (last login within 30 days)
     * @type {string}
     * @memberof SendEmailDto
     */
    recipientGroup: string;
    /**
     * Email subject (English)
     * @type {string}
     * @memberof SendEmailDto
     */
    subjectEn: string;
    /**
     * Email subject (German)
     * @type {string}
     * @memberof SendEmailDto
     */
    subjectDe: string;
    /**
     * Email body text (English)
     * @type {string}
     * @memberof SendEmailDto
     */
    textEn: string;
    /**
     * Email body text (German)
     * @type {string}
     * @memberof SendEmailDto
     */
    textDe: string;
    /**
     * Send both language versions as test to admin email
     * @type {boolean}
     * @memberof SendEmailDto
     */
    isTest?: boolean;
}

/**
 * Check if a given object implements the SendEmailDto interface.
 */
export function instanceOfSendEmailDto(value: object): value is SendEmailDto {
    if (!('recipientGroup' in value) || value['recipientGroup'] === undefined) return false;
    if (!('subjectEn' in value) || value['subjectEn'] === undefined) return false;
    if (!('subjectDe' in value) || value['subjectDe'] === undefined) return false;
    if (!('textEn' in value) || value['textEn'] === undefined) return false;
    if (!('textDe' in value) || value['textDe'] === undefined) return false;
    return true;
}

export function SendEmailDtoFromJSON(json: any): SendEmailDto {
    return SendEmailDtoFromJSONTyped(json, false);
}

export function SendEmailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendEmailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'recipientGroup': json['recipientGroup'],
        'subjectEn': json['subjectEn'],
        'subjectDe': json['subjectDe'],
        'textEn': json['textEn'],
        'textDe': json['textDe'],
        'isTest': json['isTest'] == null ? undefined : json['isTest'],
    };
}

export function SendEmailDtoToJSON(json: any): SendEmailDto {
    return SendEmailDtoToJSONTyped(json, false);
}

export function SendEmailDtoToJSONTyped(value?: SendEmailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recipientGroup': value['recipientGroup'],
        'subjectEn': value['subjectEn'],
        'subjectDe': value['subjectDe'],
        'textEn': value['textEn'],
        'textDe': value['textDe'],
        'isTest': value['isTest'],
    };
}

