/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendEmailDto
 */
export interface SendEmailDto {
    /**
     * Recipient group: 'all', 'admins', 'account-owners', or 'custom'
     * @type {string}
     * @memberof SendEmailDto
     */
    recipientGroup: string;
    /**
     * Comma-separated list of email addresses for custom group
     * @type {string}
     * @memberof SendEmailDto
     */
    recipients?: string;
    /**
     * Email subject
     * @type {string}
     * @memberof SendEmailDto
     */
    subject: string;
    /**
     * Email body text
     * @type {string}
     * @memberof SendEmailDto
     */
    text: string;
    /**
     * Is this a test email?
     * @type {boolean}
     * @memberof SendEmailDto
     */
    isTest?: boolean;
}

/**
 * Check if a given object implements the SendEmailDto interface.
 */
export function instanceOfSendEmailDto(value: object): value is SendEmailDto {
    if (!('recipientGroup' in value) || value['recipientGroup'] === undefined) return false;
    if (!('subject' in value) || value['subject'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function SendEmailDtoFromJSON(json: any): SendEmailDto {
    return SendEmailDtoFromJSONTyped(json, false);
}

export function SendEmailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendEmailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'recipientGroup': json['recipientGroup'],
        'recipients': json['recipients'] == null ? undefined : json['recipients'],
        'subject': json['subject'],
        'text': json['text'],
        'isTest': json['isTest'] == null ? undefined : json['isTest'],
    };
}

export function SendEmailDtoToJSON(json: any): SendEmailDto {
    return SendEmailDtoToJSONTyped(json, false);
}

export function SendEmailDtoToJSONTyped(value?: SendEmailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recipientGroup': value['recipientGroup'],
        'recipients': value['recipients'],
        'subject': value['subject'],
        'text': value['text'],
        'isTest': value['isTest'],
    };
}

