/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServerDistributionDto
 */
export interface ServerDistributionDto {
    /**
     * Mastodon server URL
     * @type {string}
     * @memberof ServerDistributionDto
     */
    serverURL: string;
    /**
     * Number of accounts on this server
     * @type {number}
     * @memberof ServerDistributionDto
     */
    count: number;
}

/**
 * Check if a given object implements the ServerDistributionDto interface.
 */
export function instanceOfServerDistributionDto(value: object): value is ServerDistributionDto {
    if (!('serverURL' in value) || value['serverURL'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function ServerDistributionDtoFromJSON(json: any): ServerDistributionDto {
    return ServerDistributionDtoFromJSONTyped(json, false);
}

export function ServerDistributionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerDistributionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'serverURL': json['serverURL'],
        'count': json['count'],
    };
}

export function ServerDistributionDtoToJSON(json: any): ServerDistributionDto {
    return ServerDistributionDtoToJSONTyped(json, false);
}

export function ServerDistributionDtoToJSONTyped(value?: ServerDistributionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serverURL': value['serverURL'],
        'count': value['count'],
    };
}

