/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SessionAccountDto
 */
export interface SessionAccountDto {
    /**
     * Account ID
     * @type {string}
     * @memberof SessionAccountDto
     */
    id: string;
    /**
     * Mastodon server URL
     * @type {string}
     * @memberof SessionAccountDto
     */
    serverURL: string;
    /**
     * Account display name
     * @type {string}
     * @memberof SessionAccountDto
     */
    name?: string;
    /**
     * Mastodon username
     * @type {string}
     * @memberof SessionAccountDto
     */
    username?: string;
    /**
     * Full account name
     * @type {string}
     * @memberof SessionAccountDto
     */
    accountName?: string;
    /**
     * Mastodon account URL
     * @type {string}
     * @memberof SessionAccountDto
     */
    accountURL?: string;
    /**
     * Avatar URL
     * @type {string}
     * @memberof SessionAccountDto
     */
    avatarURL?: string;
    /**
     * Timezone of the account
     * @type {string}
     * @memberof SessionAccountDto
     */
    timezone: string;
    /**
     * UTC offset for the timezone
     * @type {string}
     * @memberof SessionAccountDto
     */
    utcOffset: string;
}

/**
 * Check if a given object implements the SessionAccountDto interface.
 */
export function instanceOfSessionAccountDto(value: object): value is SessionAccountDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('serverURL' in value) || value['serverURL'] === undefined) return false;
    if (!('timezone' in value) || value['timezone'] === undefined) return false;
    if (!('utcOffset' in value) || value['utcOffset'] === undefined) return false;
    return true;
}

export function SessionAccountDtoFromJSON(json: any): SessionAccountDto {
    return SessionAccountDtoFromJSONTyped(json, false);
}

export function SessionAccountDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionAccountDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['_id'],
        'serverURL': json['serverURL'],
        'name': json['name'] == null ? undefined : json['name'],
        'username': json['username'] == null ? undefined : json['username'],
        'accountName': json['accountName'] == null ? undefined : json['accountName'],
        'accountURL': json['accountURL'] == null ? undefined : json['accountURL'],
        'avatarURL': json['avatarURL'] == null ? undefined : json['avatarURL'],
        'timezone': json['timezone'],
        'utcOffset': json['utcOffset'],
    };
}

export function SessionAccountDtoToJSON(json: any): SessionAccountDto {
    return SessionAccountDtoToJSONTyped(json, false);
}

export function SessionAccountDtoToJSONTyped(value?: SessionAccountDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_id': value['id'],
        'serverURL': value['serverURL'],
        'name': value['name'],
        'username': value['username'],
        'accountName': value['accountName'],
        'accountURL': value['accountURL'],
        'avatarURL': value['avatarURL'],
        'timezone': value['timezone'],
        'utcOffset': value['utcOffset'],
    };
}

