/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StaleAccountDto
 */
export interface StaleAccountDto {
    /**
     * Account ID
     * @type {string}
     * @memberof StaleAccountDto
     */
    accountId: string;
    /**
     * Mastodon account name
     * @type {string}
     * @memberof StaleAccountDto
     */
    accountName: string | null;
    /**
     * Mastodon server URL
     * @type {string}
     * @memberof StaleAccountDto
     */
    serverURL: string;
    /**
     * Account owner email
     * @type {string}
     * @memberof StaleAccountDto
     */
    ownerEmail: string;
    /**
     * Last stats collection date
     * @type {string}
     * @memberof StaleAccountDto
     */
    lastStatsDate: string | null;
    /**
     * Days since last stats update
     * @type {number}
     * @memberof StaleAccountDto
     */
    daysSinceLastUpdate: number;
}

/**
 * Check if a given object implements the StaleAccountDto interface.
 */
export function instanceOfStaleAccountDto(value: object): value is StaleAccountDto {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('accountName' in value) || value['accountName'] === undefined) return false;
    if (!('serverURL' in value) || value['serverURL'] === undefined) return false;
    if (!('ownerEmail' in value) || value['ownerEmail'] === undefined) return false;
    if (!('lastStatsDate' in value) || value['lastStatsDate'] === undefined) return false;
    if (!('daysSinceLastUpdate' in value) || value['daysSinceLastUpdate'] === undefined) return false;
    return true;
}

export function StaleAccountDtoFromJSON(json: any): StaleAccountDto {
    return StaleAccountDtoFromJSONTyped(json, false);
}

export function StaleAccountDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StaleAccountDto {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'accountName': json['accountName'],
        'serverURL': json['serverURL'],
        'ownerEmail': json['ownerEmail'],
        'lastStatsDate': json['lastStatsDate'],
        'daysSinceLastUpdate': json['daysSinceLastUpdate'],
    };
}

export function StaleAccountDtoToJSON(json: any): StaleAccountDto {
    return StaleAccountDtoToJSONTyped(json, false);
}

export function StaleAccountDtoToJSONTyped(value?: StaleAccountDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'accountName': value['accountName'],
        'serverURL': value['serverURL'],
        'ownerEmail': value['ownerEmail'],
        'lastStatsDate': value['lastStatsDate'],
        'daysSinceLastUpdate': value['daysSinceLastUpdate'],
    };
}

