/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CollectionSizesDto } from './CollectionSizesDto';
import {
    CollectionSizesDtoFromJSON,
    CollectionSizesDtoFromJSONTyped,
    CollectionSizesDtoToJSON,
    CollectionSizesDtoToJSONTyped,
} from './CollectionSizesDto';
import type { DataFreshnessDto } from './DataFreshnessDto';
import {
    DataFreshnessDtoFromJSON,
    DataFreshnessDtoFromJSONTyped,
    DataFreshnessDtoToJSON,
    DataFreshnessDtoToJSONTyped,
} from './DataFreshnessDto';
import type { TimingMarginPairDto } from './TimingMarginPairDto';
import {
    TimingMarginPairDtoFromJSON,
    TimingMarginPairDtoFromJSONTyped,
    TimingMarginPairDtoToJSON,
    TimingMarginPairDtoToJSONTyped,
} from './TimingMarginPairDto';
import type { RecentFailureDto } from './RecentFailureDto';
import {
    RecentFailureDtoFromJSON,
    RecentFailureDtoFromJSONTyped,
    RecentFailureDtoToJSON,
    RecentFailureDtoToJSONTyped,
} from './RecentFailureDto';
import type { JobStatusDto } from './JobStatusDto';
import {
    JobStatusDtoFromJSON,
    JobStatusDtoFromJSONTyped,
    JobStatusDtoToJSON,
    JobStatusDtoToJSONTyped,
} from './JobStatusDto';

/**
 * 
 * @export
 * @interface SystemHealthResponseDto
 */
export interface SystemHealthResponseDto {
    /**
     * When the health snapshot was generated
     * @type {string}
     * @memberof SystemHealthResponseDto
     */
    generatedAt?: string;
    /**
     * Status of each CLI job
     * @type {Array<JobStatusDto>}
     * @memberof SystemHealthResponseDto
     */
    jobStatuses: Array<JobStatusDto>;
    /**
     * Data freshness indicators
     * @type {DataFreshnessDto}
     * @memberof SystemHealthResponseDto
     */
    dataFreshness: DataFreshnessDto;
    /**
     * Document counts per collection
     * @type {CollectionSizesDto}
     * @memberof SystemHealthResponseDto
     */
    collectionSizes: CollectionSizesDto;
    /**
     * Timing margin analysis for fetch/aggregate pairs
     * @type {Array<TimingMarginPairDto>}
     * @memberof SystemHealthResponseDto
     */
    timingMargins: Array<TimingMarginPairDto>;
    /**
     * Recent job failures (last 7 days)
     * @type {Array<RecentFailureDto>}
     * @memberof SystemHealthResponseDto
     */
    recentFailures: Array<RecentFailureDto>;
}

/**
 * Check if a given object implements the SystemHealthResponseDto interface.
 */
export function instanceOfSystemHealthResponseDto(value: object): value is SystemHealthResponseDto {
    if (!('jobStatuses' in value) || value['jobStatuses'] === undefined) return false;
    if (!('dataFreshness' in value) || value['dataFreshness'] === undefined) return false;
    if (!('collectionSizes' in value) || value['collectionSizes'] === undefined) return false;
    if (!('timingMargins' in value) || value['timingMargins'] === undefined) return false;
    if (!('recentFailures' in value) || value['recentFailures'] === undefined) return false;
    return true;
}

export function SystemHealthResponseDtoFromJSON(json: any): SystemHealthResponseDto {
    return SystemHealthResponseDtoFromJSONTyped(json, false);
}

export function SystemHealthResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemHealthResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'generatedAt': json['generatedAt'] == null ? undefined : json['generatedAt'],
        'jobStatuses': ((json['jobStatuses'] as Array<any>).map(JobStatusDtoFromJSON)),
        'dataFreshness': DataFreshnessDtoFromJSON(json['dataFreshness']),
        'collectionSizes': CollectionSizesDtoFromJSON(json['collectionSizes']),
        'timingMargins': ((json['timingMargins'] as Array<any>).map(TimingMarginPairDtoFromJSON)),
        'recentFailures': ((json['recentFailures'] as Array<any>).map(RecentFailureDtoFromJSON)),
    };
}

export function SystemHealthResponseDtoToJSON(json: any): SystemHealthResponseDto {
    return SystemHealthResponseDtoToJSONTyped(json, false);
}

export function SystemHealthResponseDtoToJSONTyped(value?: SystemHealthResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'generatedAt': value['generatedAt'],
        'jobStatuses': ((value['jobStatuses'] as Array<any>).map(JobStatusDtoToJSON)),
        'dataFreshness': DataFreshnessDtoToJSON(value['dataFreshness']),
        'collectionSizes': CollectionSizesDtoToJSON(value['collectionSizes']),
        'timingMargins': ((value['timingMargins'] as Array<any>).map(TimingMarginPairDtoToJSON)),
        'recentFailures': ((value['recentFailures'] as Array<any>).map(RecentFailureDtoToJSON)),
    };
}

