/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimingMarginDetailDto
 */
export interface TimingMarginDetailDto {
    /**
     * When the aggregate job started
     * @type {string}
     * @memberof TimingMarginDetailDto
     */
    aggregateStartedAt: string;
    /**
     * When the preceding fetch completed
     * @type {string}
     * @memberof TimingMarginDetailDto
     */
    fetchCompletedAt: string | null;
    /**
     * Time margin in ms between fetch end and aggregate start
     * @type {number}
     * @memberof TimingMarginDetailDto
     */
    marginMs: number | null;
    /**
     * Whether a fetch was still running when aggregate started
     * @type {boolean}
     * @memberof TimingMarginDetailDto
     */
    hadOverlap: boolean;
}

/**
 * Check if a given object implements the TimingMarginDetailDto interface.
 */
export function instanceOfTimingMarginDetailDto(value: object): value is TimingMarginDetailDto {
    if (!('aggregateStartedAt' in value) || value['aggregateStartedAt'] === undefined) return false;
    if (!('fetchCompletedAt' in value) || value['fetchCompletedAt'] === undefined) return false;
    if (!('marginMs' in value) || value['marginMs'] === undefined) return false;
    if (!('hadOverlap' in value) || value['hadOverlap'] === undefined) return false;
    return true;
}

export function TimingMarginDetailDtoFromJSON(json: any): TimingMarginDetailDto {
    return TimingMarginDetailDtoFromJSONTyped(json, false);
}

export function TimingMarginDetailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimingMarginDetailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'aggregateStartedAt': json['aggregateStartedAt'],
        'fetchCompletedAt': json['fetchCompletedAt'],
        'marginMs': json['marginMs'],
        'hadOverlap': json['hadOverlap'],
    };
}

export function TimingMarginDetailDtoToJSON(json: any): TimingMarginDetailDto {
    return TimingMarginDetailDtoToJSONTyped(json, false);
}

export function TimingMarginDetailDtoToJSONTyped(value?: TimingMarginDetailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'aggregateStartedAt': value['aggregateStartedAt'],
        'fetchCompletedAt': value['fetchCompletedAt'],
        'marginMs': value['marginMs'],
        'hadOverlap': value['hadOverlap'],
    };
}

