/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimingMarginDetailDto } from './TimingMarginDetailDto';
import {
    TimingMarginDetailDtoFromJSON,
    TimingMarginDetailDtoFromJSONTyped,
    TimingMarginDetailDtoToJSON,
    TimingMarginDetailDtoToJSONTyped,
} from './TimingMarginDetailDto';

/**
 * 
 * @export
 * @interface TimingMarginSummaryDto
 */
export interface TimingMarginSummaryDto {
    /**
     * Number of samples in the analysis period
     * @type {number}
     * @memberof TimingMarginSummaryDto
     */
    sampleCount: number;
    /**
     * Number of times fetch and aggregate overlapped
     * @type {number}
     * @memberof TimingMarginSummaryDto
     */
    overlapCount: number;
    /**
     * Minimum margin in ms
     * @type {number}
     * @memberof TimingMarginSummaryDto
     */
    minMarginMs: number | null;
    /**
     * Maximum margin in ms
     * @type {number}
     * @memberof TimingMarginSummaryDto
     */
    maxMarginMs: number | null;
    /**
     * Average margin in ms
     * @type {number}
     * @memberof TimingMarginSummaryDto
     */
    avgMarginMs: number | null;
    /**
     * Per-run details
     * @type {Array<TimingMarginDetailDto>}
     * @memberof TimingMarginSummaryDto
     */
    details: Array<TimingMarginDetailDto>;
}

/**
 * Check if a given object implements the TimingMarginSummaryDto interface.
 */
export function instanceOfTimingMarginSummaryDto(value: object): value is TimingMarginSummaryDto {
    if (!('sampleCount' in value) || value['sampleCount'] === undefined) return false;
    if (!('overlapCount' in value) || value['overlapCount'] === undefined) return false;
    if (!('minMarginMs' in value) || value['minMarginMs'] === undefined) return false;
    if (!('maxMarginMs' in value) || value['maxMarginMs'] === undefined) return false;
    if (!('avgMarginMs' in value) || value['avgMarginMs'] === undefined) return false;
    if (!('details' in value) || value['details'] === undefined) return false;
    return true;
}

export function TimingMarginSummaryDtoFromJSON(json: any): TimingMarginSummaryDto {
    return TimingMarginSummaryDtoFromJSONTyped(json, false);
}

export function TimingMarginSummaryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimingMarginSummaryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'sampleCount': json['sampleCount'],
        'overlapCount': json['overlapCount'],
        'minMarginMs': json['minMarginMs'],
        'maxMarginMs': json['maxMarginMs'],
        'avgMarginMs': json['avgMarginMs'],
        'details': ((json['details'] as Array<any>).map(TimingMarginDetailDtoFromJSON)),
    };
}

export function TimingMarginSummaryDtoToJSON(json: any): TimingMarginSummaryDto {
    return TimingMarginSummaryDtoToJSONTyped(json, false);
}

export function TimingMarginSummaryDtoToJSONTyped(value?: TimingMarginSummaryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sampleCount': value['sampleCount'],
        'overlapCount': value['overlapCount'],
        'minMarginMs': value['minMarginMs'],
        'maxMarginMs': value['maxMarginMs'],
        'avgMarginMs': value['avgMarginMs'],
        'details': ((value['details'] as Array<any>).map(TimingMarginDetailDtoToJSON)),
    };
}

