/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimingMarginSummaryDto } from './TimingMarginSummaryDto';
import {
    TimingMarginSummaryDtoFromJSON,
    TimingMarginSummaryDtoFromJSONTyped,
    TimingMarginSummaryDtoToJSON,
    TimingMarginSummaryDtoToJSONTyped,
} from './TimingMarginSummaryDto';

/**
 * 
 * @export
 * @interface TimingMarginPairDto
 */
export interface TimingMarginPairDto {
    /**
     * Fetch job name
     * @type {string}
     * @memberof TimingMarginPairDto
     */
    fetchJob: string;
    /**
     * Aggregate job name
     * @type {string}
     * @memberof TimingMarginPairDto
     */
    aggregateJob: string;
    /**
     * Timing analysis for last 7 days
     * @type {TimingMarginSummaryDto}
     * @memberof TimingMarginPairDto
     */
    last7Days: TimingMarginSummaryDto;
}

/**
 * Check if a given object implements the TimingMarginPairDto interface.
 */
export function instanceOfTimingMarginPairDto(value: object): value is TimingMarginPairDto {
    if (!('fetchJob' in value) || value['fetchJob'] === undefined) return false;
    if (!('aggregateJob' in value) || value['aggregateJob'] === undefined) return false;
    if (!('last7Days' in value) || value['last7Days'] === undefined) return false;
    return true;
}

export function TimingMarginPairDtoFromJSON(json: any): TimingMarginPairDto {
    return TimingMarginPairDtoFromJSONTyped(json, false);
}

export function TimingMarginPairDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimingMarginPairDto {
    if (json == null) {
        return json;
    }
    return {
        
        'fetchJob': json['fetchJob'],
        'aggregateJob': json['aggregateJob'],
        'last7Days': TimingMarginSummaryDtoFromJSON(json['last7Days']),
    };
}

export function TimingMarginPairDtoToJSON(json: any): TimingMarginPairDto {
    return TimingMarginPairDtoToJSONTyped(json, false);
}

export function TimingMarginPairDtoToJSONTyped(value?: TimingMarginPairDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fetchJob': value['fetchJob'],
        'aggregateJob': value['aggregateJob'],
        'last7Days': TimingMarginSummaryDtoToJSON(value['last7Days']),
    };
}

