/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenResponseDto
 */
export interface TokenResponseDto {
    /**
     * JWT Access Token
     * @type {string}
     * @memberof TokenResponseDto
     */
    accessToken: string;
    /**
     * JWT Refresh Token
     * @type {string}
     * @memberof TokenResponseDto
     */
    refreshToken: string;
}

/**
 * Check if a given object implements the TokenResponseDto interface.
 */
export function instanceOfTokenResponseDto(value: object): value is TokenResponseDto {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    return true;
}

export function TokenResponseDtoFromJSON(json: any): TokenResponseDto {
    return TokenResponseDtoFromJSONTyped(json, false);
}

export function TokenResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'],
        'refreshToken': json['refreshToken'],
    };
}

export function TokenResponseDtoToJSON(json: any): TokenResponseDto {
    return TokenResponseDtoToJSONTyped(json, false);
}

export function TokenResponseDtoToJSONTyped(value?: TokenResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

