/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RankedTootDto } from './RankedTootDto';
import {
    RankedTootDtoFromJSON,
    RankedTootDtoFromJSONTyped,
    RankedTootDtoToJSON,
    RankedTootDtoToJSONTyped,
} from './RankedTootDto';

/**
 * 
 * @export
 * @interface TopTootsCategoryDto
 */
export interface TopTootsCategoryDto {
    /**
     * List of ranked toots
     * @type {Array<RankedTootDto>}
     * @memberof TopTootsCategoryDto
     */
    data: Array<RankedTootDto>;
    /**
     * The timeframe used for fetching these toots
     * @type {string}
     * @memberof TopTootsCategoryDto
     */
    timeframe: string;
}

/**
 * Check if a given object implements the TopTootsCategoryDto interface.
 */
export function instanceOfTopTootsCategoryDto(value: object): value is TopTootsCategoryDto {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('timeframe' in value) || value['timeframe'] === undefined) return false;
    return true;
}

export function TopTootsCategoryDtoFromJSON(json: any): TopTootsCategoryDto {
    return TopTootsCategoryDtoFromJSONTyped(json, false);
}

export function TopTootsCategoryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopTootsCategoryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(RankedTootDtoFromJSON)),
        'timeframe': json['timeframe'],
    };
}

export function TopTootsCategoryDtoToJSON(json: any): TopTootsCategoryDto {
    return TopTootsCategoryDtoToJSONTyped(json, false);
}

export function TopTootsCategoryDtoToJSONTyped(value?: TopTootsCategoryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(RankedTootDtoToJSON)),
        'timeframe': value['timeframe'],
    };
}

