/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAccountDto
 */
export interface UpdateAccountDto {
    /**
     * A new custom name for the account
     * @type {string}
     * @memberof UpdateAccountDto
     */
    name?: string;
    /**
     * The new timezone for the account
     * @type {string}
     * @memberof UpdateAccountDto
     */
    timezone?: string;
}

/**
 * Check if a given object implements the UpdateAccountDto interface.
 */
export function instanceOfUpdateAccountDto(value: object): value is UpdateAccountDto {
    return true;
}

export function UpdateAccountDtoFromJSON(json: any): UpdateAccountDto {
    return UpdateAccountDtoFromJSONTyped(json, false);
}

export function UpdateAccountDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAccountDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
    };
}

export function UpdateAccountDtoToJSON(json: any): UpdateAccountDto {
    return UpdateAccountDtoToJSONTyped(json, false);
}

export function UpdateAccountDtoToJSONTyped(value?: UpdateAccountDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'timezone': value['timezone'],
    };
}

