/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserResponseDto
 */
export interface UserResponseDto {
    /**
     * User ID
     * @type {string}
     * @memberof UserResponseDto
     */
    id: string;
    /**
     * User email address
     * @type {string}
     * @memberof UserResponseDto
     */
    email: string;
    /**
     * User role
     * @type {string}
     * @memberof UserResponseDto
     */
    role: UserResponseDtoRoleEnum;
    /**
     * Indicates if the user account is active
     * @type {boolean}
     * @memberof UserResponseDto
     */
    isActive: boolean;
    /**
     * Timestamp of user creation
     * @type {Date}
     * @memberof UserResponseDto
     */
    createdAt: Date;
    /**
     * Timestamp of last user update
     * @type {Date}
     * @memberof UserResponseDto
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const UserResponseDtoRoleEnum = {
    Admin: 'admin',
    AccountOwner: 'account-owner'
} as const;
export type UserResponseDtoRoleEnum = typeof UserResponseDtoRoleEnum[keyof typeof UserResponseDtoRoleEnum];


/**
 * Check if a given object implements the UserResponseDto interface.
 */
export function instanceOfUserResponseDto(value: object): value is UserResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function UserResponseDtoFromJSON(json: any): UserResponseDto {
    return UserResponseDtoFromJSONTyped(json, false);
}

export function UserResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'role': json['role'],
        'isActive': json['isActive'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function UserResponseDtoToJSON(json: any): UserResponseDto {
    return UserResponseDtoToJSONTyped(json, false);
}

export function UserResponseDtoToJSONTyped(value?: UserResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'role': value['role'],
        'isActive': value['isActive'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

