/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoleBreakdownDto } from './RoleBreakdownDto';
import {
    RoleBreakdownDtoFromJSON,
    RoleBreakdownDtoFromJSONTyped,
    RoleBreakdownDtoToJSON,
    RoleBreakdownDtoToJSONTyped,
} from './RoleBreakdownDto';
import type { LoginActivityDto } from './LoginActivityDto';
import {
    LoginActivityDtoFromJSON,
    LoginActivityDtoFromJSONTyped,
    LoginActivityDtoToJSON,
    LoginActivityDtoToJSONTyped,
} from './LoginActivityDto';
import type { RegistrationTrendDto } from './RegistrationTrendDto';
import {
    RegistrationTrendDtoFromJSON,
    RegistrationTrendDtoFromJSONTyped,
    RegistrationTrendDtoToJSON,
    RegistrationTrendDtoToJSONTyped,
} from './RegistrationTrendDto';

/**
 * 
 * @export
 * @interface UserMetricsDto
 */
export interface UserMetricsDto {
    /**
     * Total number of users
     * @type {number}
     * @memberof UserMetricsDto
     */
    totalCount: number;
    /**
     * Number of active users
     * @type {number}
     * @memberof UserMetricsDto
     */
    activeCount: number;
    /**
     * Number of inactive users
     * @type {number}
     * @memberof UserMetricsDto
     */
    inactiveCount: number;
    /**
     * Number of users with verified email
     * @type {number}
     * @memberof UserMetricsDto
     */
    emailVerifiedCount: number;
    /**
     * Breakdown of users by role
     * @type {RoleBreakdownDto}
     * @memberof UserMetricsDto
     */
    roleBreakdown: RoleBreakdownDto;
    /**
     * Registration trends over the last 30 days
     * @type {RegistrationTrendDto}
     * @memberof UserMetricsDto
     */
    registrations: RegistrationTrendDto;
    /**
     * Login activity over various timeframes
     * @type {LoginActivityDto}
     * @memberof UserMetricsDto
     */
    loginActivity: LoginActivityDto;
}

/**
 * Check if a given object implements the UserMetricsDto interface.
 */
export function instanceOfUserMetricsDto(value: object): value is UserMetricsDto {
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('activeCount' in value) || value['activeCount'] === undefined) return false;
    if (!('inactiveCount' in value) || value['inactiveCount'] === undefined) return false;
    if (!('emailVerifiedCount' in value) || value['emailVerifiedCount'] === undefined) return false;
    if (!('roleBreakdown' in value) || value['roleBreakdown'] === undefined) return false;
    if (!('registrations' in value) || value['registrations'] === undefined) return false;
    if (!('loginActivity' in value) || value['loginActivity'] === undefined) return false;
    return true;
}

export function UserMetricsDtoFromJSON(json: any): UserMetricsDto {
    return UserMetricsDtoFromJSONTyped(json, false);
}

export function UserMetricsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserMetricsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'totalCount': json['totalCount'],
        'activeCount': json['activeCount'],
        'inactiveCount': json['inactiveCount'],
        'emailVerifiedCount': json['emailVerifiedCount'],
        'roleBreakdown': RoleBreakdownDtoFromJSON(json['roleBreakdown']),
        'registrations': RegistrationTrendDtoFromJSON(json['registrations']),
        'loginActivity': LoginActivityDtoFromJSON(json['loginActivity']),
    };
}

export function UserMetricsDtoToJSON(json: any): UserMetricsDto {
    return UserMetricsDtoToJSONTyped(json, false);
}

export function UserMetricsDtoToJSONTyped(value?: UserMetricsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalCount': value['totalCount'],
        'activeCount': value['activeCount'],
        'inactiveCount': value['inactiveCount'],
        'emailVerifiedCount': value['emailVerifiedCount'],
        'roleBreakdown': RoleBreakdownDtoToJSON(value['roleBreakdown']),
        'registrations': RegistrationTrendDtoToJSON(value['registrations']),
        'loginActivity': LoginActivityDtoToJSON(value['loginActivity']),
    };
}

