/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WeeklyStatsMailDto
 */
export interface WeeklyStatsMailDto {
    /**
     * User ID
     * @type {string}
     * @memberof WeeklyStatsMailDto
     */
    userID: string;
    /**
     * Array of Account IDs for which to send weekly stats
     * @type {Array<string>}
     * @memberof WeeklyStatsMailDto
     */
    accounts: Array<string>;
    /**
     * Optional email address to reroute the weekly stats email to
     * @type {string}
     * @memberof WeeklyStatsMailDto
     */
    email?: string;
}

/**
 * Check if a given object implements the WeeklyStatsMailDto interface.
 */
export function instanceOfWeeklyStatsMailDto(value: object): value is WeeklyStatsMailDto {
    if (!('userID' in value) || value['userID'] === undefined) return false;
    if (!('accounts' in value) || value['accounts'] === undefined) return false;
    return true;
}

export function WeeklyStatsMailDtoFromJSON(json: any): WeeklyStatsMailDto {
    return WeeklyStatsMailDtoFromJSONTyped(json, false);
}

export function WeeklyStatsMailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WeeklyStatsMailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userID': json['userID'],
        'accounts': json['accounts'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function WeeklyStatsMailDtoToJSON(json: any): WeeklyStatsMailDto {
    return WeeklyStatsMailDtoToJSONTyped(json, false);
}

export function WeeklyStatsMailDtoToJSONTyped(value?: WeeklyStatsMailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userID': value['userID'],
        'accounts': value['accounts'],
        'email': value['email'],
    };
}

