version: '3.1'

services:
    application:
        image: productionbuild/analytodon:latest
        ports:
            - 80:80
        environment:
            - JWT_SECRET
            - MONGODB_URI
            - SES_HOST
            - SES_PORT
            - SES_USER
            - SES_PASSWD
            - APP_URL
            - MARKETING_URL
            - SUPPORT_EMAIL
            - EMAIL_SENDER_NAME
            - EMAIL_API_KEY
