services:
  mongodb:
    image: mongo:8
    container_name: analytodon-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: analytodon_dev
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db

  mailpit:
    image: axllent/mailpit:latest
    container_name: analytodon-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped

volumes:
  mongodb_data:
