packages:
  # all packages in subdirs of packages/ and components/
  - "packages/**"
  # all packages in subdirs of apps/
  - "apps/**"
  # exclude packages that are inside test directories
  - "!**/test/**"
