export const authConstants = {
  JWT_SECRET_KEY: 'JWT_SECRET',
  JWT_EXPIRES_IN_KEY: 'JWT_EXPIRES_IN',
  JWT_DEFAULT_SECRET: 'THIS_IS_A_DEFAULT_SECRET_CHANGE_IT', // For development only
  JWT_DEFAULT_EXPIRES_IN: '3600s', // 1 hour
  JWT_DEFAULT_EXPIRES_IN_SECONDS: 3600, // 1 hour in seconds

  // Refresh Token Configuration
  JWT_REFRESH_TOKEN_EXPIRES_IN_KEY: 'JWT_REFRESH_TOKEN_EXPIRES_IN',
  JWT_DEFAULT_REFRESH_TOKEN_EXPIRES_IN: '7d', // 7 days
};
