apiVersion: apps/v1
kind: Deployment
metadata:
    name: analytodon
    namespace: analytodon
spec:
    replicas: 1
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
    selector:
        matchLabels:
            app: analytodon
    template:
        metadata:
            labels:
                app: analytodon
        spec:
            containers:
                - name: analytodon
                  image: productionbuild/analytodon:latest
                  imagePullPolicy: Always
                  ports:
                      - name: http
                        containerPort: 80
                  env:
                      - name: NEWRELIC_LICENSE_KEY
                        valueFrom:
                            secretKeyRef:
                                name: newrelic-secret
                                key: license-key
                      - name: JWT_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: jwt-secret
                                key: secret
                      - name: MONGODB_URI
                        valueFrom:
                            secretKeyRef:
                                name: mongodb-secret
                                key: uri
                      - name: SES_HOST
                        valueFrom:
                            secretKeyRef:
                                name: email-secret
                                key: host
                      - name: SES_PORT
                        valueFrom:
                            secretKeyRef:
                                name: email-secret
                                key: port
                      - name: SES_USER
                        valueFrom:
                            secretKeyRef:
                                name: email-secret
                                key: user
                      - name: SES_PASSWD
                        valueFrom:
                            secretKeyRef:
                                name: email-secret
                                key: password
                      - name: EMAIL_API_KEY
                        valueFrom:
                            secretKeyRef:
                                name: emailapi-secret
                                key: key
                  startupProbe:
                      failureThreshold: 120
                      httpGet:
                          path: /
                          port: http
                  readinessProbe:
                      httpGet:
                          path: /login
                          port: http
                  resources:
                      requests:
                          memory: '20Mi'
                          cpu: '100m'
                      limits:
                          memory: '256Mi'
                          cpu: '500m'
---
apiVersion: v1
kind: Service
metadata:
    name: analytodon
    namespace: analytodon
spec:
    selector:
        app: analytodon
    ports:
        - port: 80
          targetPort: http
    type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: analytodon-ingress
    namespace: analytodon
    annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
spec:
    tls:
        - hosts:
              - app.analytodon.com
          secretName: letsencrypt-analytodon-tls
    rules:
        - host: 'app.analytodon.com'
          http:
              paths:
                  - pathType: Prefix
                    path: '/'
                    backend:
                        service:
                            name: analytodon
                            port:
                                number: 80
