/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccountHealthResponseDto,
  AdminStatsResponseDto,
  SystemHealthResponseDto,
} from '../models/index';
import {
    AccountHealthResponseDtoFromJSON,
    AccountHealthResponseDtoToJSON,
    AdminStatsResponseDtoFromJSON,
    AdminStatsResponseDtoToJSON,
    SystemHealthResponseDtoFromJSON,
    SystemHealthResponseDtoToJSON,
} from '../models/index';

/**
 * 
 */
export class AdminApi extends runtime.BaseAPI {

    /**
     * Get account health report (Admin)
     */
    async adminControllerGetAccountHealthRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountHealthResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/admin/accounts/health`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountHealthResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get account health report (Admin)
     */
    async adminControllerGetAccountHealth(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountHealthResponseDto> {
        const response = await this.adminControllerGetAccountHealthRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get platform overview statistics (Admin)
     */
    async adminControllerGetStatsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminStatsResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/admin/stats`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminStatsResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get platform overview statistics (Admin)
     */
    async adminControllerGetStats(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminStatsResponseDto> {
        const response = await this.adminControllerGetStatsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get system health report (Admin)
     */
    async adminControllerGetSystemHealthRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SystemHealthResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/admin/system/health`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SystemHealthResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get system health report (Admin)
     */
    async adminControllerGetSystemHealth(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SystemHealthResponseDto> {
        const response = await this.adminControllerGetSystemHealthRaw(initOverrides);
        return await response.value();
    }

}
