/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChartDataPointDto,
  FollowersKpiDto,
  TotalSnapshotDto,
} from '../models/index';
import {
    ChartDataPointDtoFromJSON,
    ChartDataPointDtoToJSON,
    FollowersKpiDtoFromJSON,
    FollowersKpiDtoToJSON,
    TotalSnapshotDtoFromJSON,
    TotalSnapshotDtoToJSON,
} from '../models/index';

export interface FollowersControllerExportCsvRequest {
    accountId: string;
    timeframe: string;
}

export interface FollowersControllerGetChartDataRequest {
    accountId: string;
    timeframe: string;
}

export interface FollowersControllerGetMonthlyKpiRequest {
    accountId: string;
}

export interface FollowersControllerGetTotalSnapshotRequest {
    accountId: string;
}

export interface FollowersControllerGetWeeklyKpiRequest {
    accountId: string;
}

export interface FollowersControllerGetYearlyKpiRequest {
    accountId: string;
}

/**
 * 
 */
export class FollowersApi extends runtime.BaseAPI {

    /**
     * Export followers data as CSV for an account over a specified timeframe
     */
    async followersControllerExportCsvRaw(requestParameters: FollowersControllerExportCsvRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling followersControllerExportCsv().'
            );
        }

        if (requestParameters['timeframe'] == null) {
            throw new runtime.RequiredError(
                'timeframe',
                'Required parameter "timeframe" was null or undefined when calling followersControllerExportCsv().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['timeframe'] != null) {
            queryParameters['timeframe'] = requestParameters['timeframe'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts/{accountId}/followers/csv`.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Export followers data as CSV for an account over a specified timeframe
     */
    async followersControllerExportCsv(requestParameters: FollowersControllerExportCsvRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.followersControllerExportCsvRaw(requestParameters, initOverrides);
    }

    /**
     * Get chart data for an account\'s followers over a specified timeframe
     */
    async followersControllerGetChartDataRaw(requestParameters: FollowersControllerGetChartDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ChartDataPointDto>>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling followersControllerGetChartData().'
            );
        }

        if (requestParameters['timeframe'] == null) {
            throw new runtime.RequiredError(
                'timeframe',
                'Required parameter "timeframe" was null or undefined when calling followersControllerGetChartData().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['timeframe'] != null) {
            queryParameters['timeframe'] = requestParameters['timeframe'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts/{accountId}/followers/chart`.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ChartDataPointDtoFromJSON));
    }

    /**
     * Get chart data for an account\'s followers over a specified timeframe
     */
    async followersControllerGetChartData(requestParameters: FollowersControllerGetChartDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ChartDataPointDto>> {
        const response = await this.followersControllerGetChartDataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get monthly Key Performance Indicators (KPIs) for an account\'s followers
     */
    async followersControllerGetMonthlyKpiRaw(requestParameters: FollowersControllerGetMonthlyKpiRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FollowersKpiDto>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling followersControllerGetMonthlyKpi().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts/{accountId}/followers/kpi/monthly`.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FollowersKpiDtoFromJSON(jsonValue));
    }

    /**
     * Get monthly Key Performance Indicators (KPIs) for an account\'s followers
     */
    async followersControllerGetMonthlyKpi(requestParameters: FollowersControllerGetMonthlyKpiRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FollowersKpiDto> {
        const response = await this.followersControllerGetMonthlyKpiRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get total snapshot of an account\'s followers
     */
    async followersControllerGetTotalSnapshotRaw(requestParameters: FollowersControllerGetTotalSnapshotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TotalSnapshotDto>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling followersControllerGetTotalSnapshot().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts/{accountId}/followers/kpi/total`.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TotalSnapshotDtoFromJSON(jsonValue));
    }

    /**
     * Get total snapshot of an account\'s followers
     */
    async followersControllerGetTotalSnapshot(requestParameters: FollowersControllerGetTotalSnapshotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TotalSnapshotDto> {
        const response = await this.followersControllerGetTotalSnapshotRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get weekly Key Performance Indicators (KPIs) for an account\'s followers
     */
    async followersControllerGetWeeklyKpiRaw(requestParameters: FollowersControllerGetWeeklyKpiRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FollowersKpiDto>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling followersControllerGetWeeklyKpi().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts/{accountId}/followers/kpi/weekly`.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FollowersKpiDtoFromJSON(jsonValue));
    }

    /**
     * Get weekly Key Performance Indicators (KPIs) for an account\'s followers
     */
    async followersControllerGetWeeklyKpi(requestParameters: FollowersControllerGetWeeklyKpiRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FollowersKpiDto> {
        const response = await this.followersControllerGetWeeklyKpiRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get yearly Key Performance Indicators (KPIs) for an account\'s followers
     */
    async followersControllerGetYearlyKpiRaw(requestParameters: FollowersControllerGetYearlyKpiRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FollowersKpiDto>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling followersControllerGetYearlyKpi().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts/{accountId}/followers/kpi/yearly`.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FollowersKpiDtoFromJSON(jsonValue));
    }

    /**
     * Get yearly Key Performance Indicators (KPIs) for an account\'s followers
     */
    async followersControllerGetYearlyKpi(requestParameters: FollowersControllerGetYearlyKpiRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FollowersKpiDto> {
        const response = await this.followersControllerGetYearlyKpiRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
