/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HashtagEngagementDto,
  HashtagOverTimeDto,
  HashtagTopDto,
} from '../models/index';
import {
    HashtagEngagementDtoFromJSON,
    HashtagEngagementDtoToJSON,
    HashtagOverTimeDtoFromJSON,
    HashtagOverTimeDtoToJSON,
    HashtagTopDtoFromJSON,
    HashtagTopDtoToJSON,
} from '../models/index';

export interface HashtagsControllerGetEngagementRequest {
    accountId: string;
    timeframe: string;
    limit?: number;
}

export interface HashtagsControllerGetMostEffectiveRequest {
    accountId: string;
    timeframe: string;
    limit?: number;
    minTootCount?: number;
}

export interface HashtagsControllerGetOverTimeRequest {
    accountId: string;
    timeframe: string;
    limit?: number;
}

export interface HashtagsControllerGetTopHashtagsRequest {
    accountId: string;
    timeframe: string;
    limit?: number;
}

/**
 * 
 */
export class HashtagsApi extends runtime.BaseAPI {

    /**
     * Get hashtag engagement metrics for an account
     */
    async hashtagsControllerGetEngagementRaw(requestParameters: HashtagsControllerGetEngagementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<HashtagEngagementDto>>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling hashtagsControllerGetEngagement().'
            );
        }

        if (requestParameters['timeframe'] == null) {
            throw new runtime.RequiredError(
                'timeframe',
                'Required parameter "timeframe" was null or undefined when calling hashtagsControllerGetEngagement().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['timeframe'] != null) {
            queryParameters['timeframe'] = requestParameters['timeframe'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts/{accountId}/hashtags/engagement`.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(HashtagEngagementDtoFromJSON));
    }

    /**
     * Get hashtag engagement metrics for an account
     */
    async hashtagsControllerGetEngagement(requestParameters: HashtagsControllerGetEngagementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<HashtagEngagementDto>> {
        const response = await this.hashtagsControllerGetEngagementRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get most effective hashtags by average engagement per toot
     */
    async hashtagsControllerGetMostEffectiveRaw(requestParameters: HashtagsControllerGetMostEffectiveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<HashtagEngagementDto>>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling hashtagsControllerGetMostEffective().'
            );
        }

        if (requestParameters['timeframe'] == null) {
            throw new runtime.RequiredError(
                'timeframe',
                'Required parameter "timeframe" was null or undefined when calling hashtagsControllerGetMostEffective().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['timeframe'] != null) {
            queryParameters['timeframe'] = requestParameters['timeframe'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['minTootCount'] != null) {
            queryParameters['minTootCount'] = requestParameters['minTootCount'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts/{accountId}/hashtags/most-effective`.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(HashtagEngagementDtoFromJSON));
    }

    /**
     * Get most effective hashtags by average engagement per toot
     */
    async hashtagsControllerGetMostEffective(requestParameters: HashtagsControllerGetMostEffectiveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<HashtagEngagementDto>> {
        const response = await this.hashtagsControllerGetMostEffectiveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get hashtag usage over time for an account
     */
    async hashtagsControllerGetOverTimeRaw(requestParameters: HashtagsControllerGetOverTimeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HashtagOverTimeDto>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling hashtagsControllerGetOverTime().'
            );
        }

        if (requestParameters['timeframe'] == null) {
            throw new runtime.RequiredError(
                'timeframe',
                'Required parameter "timeframe" was null or undefined when calling hashtagsControllerGetOverTime().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['timeframe'] != null) {
            queryParameters['timeframe'] = requestParameters['timeframe'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts/{accountId}/hashtags/over-time`.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HashtagOverTimeDtoFromJSON(jsonValue));
    }

    /**
     * Get hashtag usage over time for an account
     */
    async hashtagsControllerGetOverTime(requestParameters: HashtagsControllerGetOverTimeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HashtagOverTimeDto> {
        const response = await this.hashtagsControllerGetOverTimeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get top hashtags by usage for an account over a specified timeframe
     */
    async hashtagsControllerGetTopHashtagsRaw(requestParameters: HashtagsControllerGetTopHashtagsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<HashtagTopDto>>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling hashtagsControllerGetTopHashtags().'
            );
        }

        if (requestParameters['timeframe'] == null) {
            throw new runtime.RequiredError(
                'timeframe',
                'Required parameter "timeframe" was null or undefined when calling hashtagsControllerGetTopHashtags().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['timeframe'] != null) {
            queryParameters['timeframe'] = requestParameters['timeframe'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts/{accountId}/hashtags/top`.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(HashtagTopDtoFromJSON));
    }

    /**
     * Get top hashtags by usage for an account over a specified timeframe
     */
    async hashtagsControllerGetTopHashtags(requestParameters: HashtagsControllerGetTopHashtagsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<HashtagTopDto>> {
        const response = await this.hashtagsControllerGetTopHashtagsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
