/* tslint:disable */
/* eslint-disable */
/**
 * Analytodon API
 * This is the API documentation for Analytodon - the open-source Mastodon analytics tool.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChartDataPointDto,
  RepliedTootDto,
  RepliesKpiDto,
  TotalSnapshotDto,
} from '../models/index';
import {
    ChartDataPointDtoFromJSON,
    ChartDataPointDtoToJSON,
    RepliedTootDtoFromJSON,
    RepliedTootDtoToJSON,
    RepliesKpiDtoFromJSON,
    RepliesKpiDtoToJSON,
    TotalSnapshotDtoFromJSON,
    TotalSnapshotDtoToJSON,
} from '../models/index';

export interface RepliesControllerExportCsvRequest {
    accountId: string;
    timeframe: string;
}

export interface RepliesControllerGetChartDataRequest {
    accountId: string;
    timeframe: string;
}

export interface RepliesControllerGetMonthlyKpiRequest {
    accountId: string;
}

export interface RepliesControllerGetTopTootsByRepliesRequest {
    accountId: string;
    timeframe: string;
}

export interface RepliesControllerGetTotalSnapshotRequest {
    accountId: string;
}

export interface RepliesControllerGetWeeklyKpiRequest {
    accountId: string;
}

export interface RepliesControllerGetYearlyKpiRequest {
    accountId: string;
}

/**
 * 
 */
export class RepliesApi extends runtime.BaseAPI {

    /**
     * Export replies data as CSV for an account over a specified timeframe
     */
    async repliesControllerExportCsvRaw(requestParameters: RepliesControllerExportCsvRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling repliesControllerExportCsv().'
            );
        }

        if (requestParameters['timeframe'] == null) {
            throw new runtime.RequiredError(
                'timeframe',
                'Required parameter "timeframe" was null or undefined when calling repliesControllerExportCsv().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['timeframe'] != null) {
            queryParameters['timeframe'] = requestParameters['timeframe'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts/{accountId}/replies/csv`.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Export replies data as CSV for an account over a specified timeframe
     */
    async repliesControllerExportCsv(requestParameters: RepliesControllerExportCsvRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.repliesControllerExportCsvRaw(requestParameters, initOverrides);
    }

    /**
     * Get chart data for an account\'s replies over a specified timeframe
     */
    async repliesControllerGetChartDataRaw(requestParameters: RepliesControllerGetChartDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ChartDataPointDto>>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling repliesControllerGetChartData().'
            );
        }

        if (requestParameters['timeframe'] == null) {
            throw new runtime.RequiredError(
                'timeframe',
                'Required parameter "timeframe" was null or undefined when calling repliesControllerGetChartData().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['timeframe'] != null) {
            queryParameters['timeframe'] = requestParameters['timeframe'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts/{accountId}/replies/chart`.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ChartDataPointDtoFromJSON));
    }

    /**
     * Get chart data for an account\'s replies over a specified timeframe
     */
    async repliesControllerGetChartData(requestParameters: RepliesControllerGetChartDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ChartDataPointDto>> {
        const response = await this.repliesControllerGetChartDataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get monthly Key Performance Indicators (KPIs) for an account\'s replies
     */
    async repliesControllerGetMonthlyKpiRaw(requestParameters: RepliesControllerGetMonthlyKpiRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RepliesKpiDto>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling repliesControllerGetMonthlyKpi().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts/{accountId}/replies/kpi/monthly`.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RepliesKpiDtoFromJSON(jsonValue));
    }

    /**
     * Get monthly Key Performance Indicators (KPIs) for an account\'s replies
     */
    async repliesControllerGetMonthlyKpi(requestParameters: RepliesControllerGetMonthlyKpiRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RepliesKpiDto> {
        const response = await this.repliesControllerGetMonthlyKpiRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get top toots by replies for an account over a specified timeframe
     */
    async repliesControllerGetTopTootsByRepliesRaw(requestParameters: RepliesControllerGetTopTootsByRepliesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RepliedTootDto>>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling repliesControllerGetTopTootsByReplies().'
            );
        }

        if (requestParameters['timeframe'] == null) {
            throw new runtime.RequiredError(
                'timeframe',
                'Required parameter "timeframe" was null or undefined when calling repliesControllerGetTopTootsByReplies().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['timeframe'] != null) {
            queryParameters['timeframe'] = requestParameters['timeframe'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts/{accountId}/replies/top-toots`.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RepliedTootDtoFromJSON));
    }

    /**
     * Get top toots by replies for an account over a specified timeframe
     */
    async repliesControllerGetTopTootsByReplies(requestParameters: RepliesControllerGetTopTootsByRepliesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RepliedTootDto>> {
        const response = await this.repliesControllerGetTopTootsByRepliesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get total snapshot of an account\'s replies
     */
    async repliesControllerGetTotalSnapshotRaw(requestParameters: RepliesControllerGetTotalSnapshotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TotalSnapshotDto>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling repliesControllerGetTotalSnapshot().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts/{accountId}/replies/kpi/total`.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TotalSnapshotDtoFromJSON(jsonValue));
    }

    /**
     * Get total snapshot of an account\'s replies
     */
    async repliesControllerGetTotalSnapshot(requestParameters: RepliesControllerGetTotalSnapshotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TotalSnapshotDto> {
        const response = await this.repliesControllerGetTotalSnapshotRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get weekly Key Performance Indicators (KPIs) for an account\'s replies
     */
    async repliesControllerGetWeeklyKpiRaw(requestParameters: RepliesControllerGetWeeklyKpiRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RepliesKpiDto>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling repliesControllerGetWeeklyKpi().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts/{accountId}/replies/kpi/weekly`.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RepliesKpiDtoFromJSON(jsonValue));
    }

    /**
     * Get weekly Key Performance Indicators (KPIs) for an account\'s replies
     */
    async repliesControllerGetWeeklyKpi(requestParameters: RepliesControllerGetWeeklyKpiRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RepliesKpiDto> {
        const response = await this.repliesControllerGetWeeklyKpiRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get yearly Key Performance Indicators (KPIs) for an account\'s replies
     */
    async repliesControllerGetYearlyKpiRaw(requestParameters: RepliesControllerGetYearlyKpiRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RepliesKpiDto>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling repliesControllerGetYearlyKpi().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts/{accountId}/replies/kpi/yearly`.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RepliesKpiDtoFromJSON(jsonValue));
    }

    /**
     * Get yearly Key Performance Indicators (KPIs) for an account\'s replies
     */
    async repliesControllerGetYearlyKpi(requestParameters: RepliesControllerGetYearlyKpiRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RepliesKpiDto> {
        const response = await this.repliesControllerGetYearlyKpiRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
