name: build

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Prepare
              run: npm ci && npm i typescript

            - name: Lint
              run: npm run lint

            - name: Build
              run: npm run build
